import hashlib,json,os,subprocess,tempfile,unittest
from pathlib import Path
from operator_packs.finex_trusted_utc_phase_d_v1 import assemble_phase_d_post_install as assembler
from operator_packs.finex_trusted_utc_v1.phase_b_asymmetric_v3 import canonical,create_attestation,create_precommit,load_bundle,materialize_loader,public_fingerprint,sha,unseal_directory_for_cleanup

def digest(raw):return hashlib.sha256(raw).hexdigest()
class InstalledDisabledAssemblerCryptoTests(unittest.TestCase):
 def setUp(self):
  self.ssh=Path(os.environ.get("SystemRoot",r"C:\Windows"))/"System32/OpenSSH/ssh-keygen.exe"
  if not self.ssh.is_file():self.skipTest("OpenSSH unavailable")
  self.temp=tempfile.TemporaryDirectory();self.base=Path(self.temp.name);self.root=self.base;self.case=0;self.power=Path(os.environ.get("SystemRoot",r"C:\Windows"))/"System32/WindowsPowerShell/v1.0/powershell.exe"
 def tearDown(self):
  if self.base.exists():unseal_directory_for_cleanup(self.base)
  self.temp.cleanup()
 def key(self,name):
  p=self.root/name;subprocess.run([str(self.ssh),"-q","-t","ed25519","-N","","-f",str(p)],check=True,capture_output=True);return p,Path(str(p)+".pub")
 def role(self,profile,short,role,index):
  signer="putra-phase-d-operator"if profile=="putra"else"finex-phase-d-operator";key,pub=self.key(role);precommit=self.root/(role+"-precommit");pointer=self.root/(role+"-current.json");generation_id=str(index)*32;att=self.root/(role+"-attestations")/generation_id/"attestation.json";bindings=self.root/(role+"-bindings.json");firewall=self.root/(role+"-firewall.json");bindings.write_bytes(canonical({"schema_version":"test-bindings-v1"}));firewall.write_bytes(canonical({"phase":"absent"}));pub_raw=pub.read_bytes();import base64;blob=base64.b64decode(pub.read_text("ascii").split()[1])
  task_name={"finex-cas":"AI_SCALPER_FINEX_TRUSTED_UTC_CAS_RESPONDER_V1","finex-fetcher":"AI_SCALPER_FINEX_TRUSTED_UTC_FETCHER_V1","putra-producer":"AI_SCALPER_FINEX_TRUSTED_UTC_PRODUCER_V1"}[role];template={"action":{"arguments":{"encoded_loader":{"future_pointer_sha256":{"name":"future_pointer_sha256","type":"sha256"},"kind":"phase-b-loader-v3"},"prefix":"-NoProfile -NonInteractive -EncodedCommand "},"execute":str(self.power.resolve())},"principal":{"logon_type":"Interactive","run_level":"Highest","user_id":"host\\operator"},"schema_version":"finex-task-definition-template-v3","settings":{"execution_time_limit_seconds":0},"task_name":task_name,"task_path":"\\"}
  named={"ReadinessChallengePath":str((self.root/(role+"-challenge.json")).resolve()),"ReadinessReceiptPath":str((self.root/(role+"-readiness.json")).resolve()),"ReadinessRole":{"finex-cas":"cas_responder","finex-fetcher":"fetcher","putra-producer":"producer"}[role]}
  if role=="finex-cas":named.update({"AcceptanceCoreSha256":"1"*64,"ConfigSha256":"2"*64,"EntrypointSha256":"3"*64,"ResponderCoreSha256":"4"*64,"SelfSha256":"5"*64})
  elif role=="finex-fetcher":named.update({"CoreSha256":"1"*64,"PublicKeyFileSha256":"2"*64,"RunnerSha256":"3"*64})
  else:named.update({"AcceptancePublicKeyFileSha256":"1"*64,"AcceptanceVerifierSha256":"2"*64,"CoreSha256":"3"*64,"RunnerSha256":"4"*64})
  invocation={"attestation_path":str(att.resolve()),"attestation_signature_path":str(Path(str(att.resolve())+".sig")),"config_and_key_bindings_path":str(bindings.resolve()),"firewall_path":str(firewall.resolve()),"observer_path":str((self.root/"observer.ps1").resolve()),"observer_sha256":"3"*64,"precommit_root":str(precommit.resolve()),"public_key_file_sha256":sha(pub_raw),"public_key_fingerprint_sha256":sha(blob),"public_key_path":str(pub.resolve()),"python_path":str(Path(os.sys.executable).resolve()),"python_sha256":"4"*64,"runtime_arguments":{"named":named,"positionals":[]},"runtime_path":str((self.root/"runtime.ps1").resolve()),"runtime_sha256":"5"*64,"ssh_keygen_path":str(self.ssh.resolve()),"ssh_keygen_sha256":sha(self.ssh.read_bytes()),"signer_identity":signer,"task_name":task_name,"task_path":"\\","v3_core_path":str((self.root/"phase_b_asymmetric_v3.py").resolve()),"v3_core_sha256":"6"*64}
  immutable={"config_and_key_bindings_sha256":sha(bindings.read_bytes()),"consumer_host_identity_sha256":"a"*64,"expected_host_role":profile,"firewall_sha256":sha(firewall.read_bytes()),"host_identity_sha256":("d"*64 if profile=="putra"else"a"*64),"joint_binding_sha256":"b"*64,"powershell_path":str(self.power.resolve()),"powershell_sha256":sha(self.power.read_bytes()),"readiness_authority":{"public_key_file_sha256":sha(pub_raw),"public_key_fingerprint_sha256":public_fingerprint(pub),"signer_identity":role+"-readiness"},"release_identity_manifest_sha256":"e"*64,"release_identity_sha256":"c"*64,"release_inventory_sha256":"9"*64,"runtime_invocation":invocation,"schema_version":"finex-phase-b-immutable-config-v3","source_host_identity_sha256":"d"*64}
  create_precommit(precommit,future_pointer_path=pointer,generation_id=generation_id,sequence=1,predecessor_generation_id="0"*32,operator_role=role,immutable_config=immutable,task_template=template,signer_identity=signer,private_key=key,ssh_keygen=self.ssh);g,graw,_,praw,_=load_bundle(precommit,pub,signer,self.ssh);loader=materialize_loader(g,graw,praw);live={"action":{"arguments":template["action"]["arguments"]["prefix"]+loader["encoded_command"],"execute":template["action"]["execute"]},"config_and_key_bindings":{"schema_version":"test-bindings-v1"},"definition_xml_sha256":"2"*64,"firewall":{"phase":"absent"},"principal":template["principal"],"settings":template["settings"],"state":"Disabled","task_name":task_name,"task_path":"\\","trigger_count":0};araw,asig=create_attestation(g,graw,praw,loader,live,key,self.ssh);att.parent.mkdir(parents=True);att.write_bytes(araw);Path(str(att)+".sig").write_bytes(asig)
  install=self.root/(role+"-install");install.mkdir();names={"finex-cas":["RUN_FINEX_TRUSTED_UTC_CAS_RESPONDER.ps1","OPERATOR_BOOTSTRAP.ps1","OPERATOR_PHASE_B.ps1","run_windows_trusted_utc_continuity_cas_responder.py","live_runtime/windows_trusted_utc_continuity_cas_responder.py","live_runtime/windows_trusted_utc_continuity_acceptance.py","responder-config.json"],"finex-fetcher":["finex_trusted_utc.py","RUN_FINEX_TRUSTED_UTC_FETCHER.ps1","OPERATOR_BOOTSTRAP.ps1","OPERATOR_PHASE_B.ps1"],"putra-producer":["finex_trusted_utc.py","RUN_PUTRA_TRUSTED_UTC_PRODUCER.ps1","OPERATOR_BOOTSTRAP.ps1","OPERATOR_PHASE_B.ps1"]}[role];files=[]
  for name in sorted(names):p=install/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(name.encode());files.append({"acl":{"owner":"owner","protected":True,"rules":[]},"path":str(p.resolve()),"sha256":sha(p.read_bytes())})
  if role=="finex-cas":metadata={"acceptance_core_sha256":named["AcceptanceCoreSha256"],"bootstrap_sha256":"7"*64,"config_sha256":named["ConfigSha256"],"entrypoint_sha256":named["EntrypointSha256"],"powershell_sha256":"8"*64,"python_sha256":"9"*64,"responder_core_sha256":named["ResponderCoreSha256"],"runner_sha256":named["SelfSha256"]}
  elif role=="finex-fetcher":metadata={"authority_public_key_sha256":"1"*64,"binding_sha256":"b"*64,"bootstrap_sha256":"2"*64,"consumer_host_identity_sha256":"a"*64,"core_sha256":named["CoreSha256"],"public_key_file_sha256":named["PublicKeyFileSha256"],"python_sha256":"4"*64,"runner_sha256":named["RunnerSha256"],"source_host_identity_sha256":"d"*64,"ssh_keygen_sha256":"5"*64}
  else:metadata={"acceptance_custody_issuer_id":"issuer","acceptance_custody_key_id":"key","acceptance_public_key_file_sha256":named["AcceptancePublicKeyFileSha256"],"acceptance_public_key_sha256":"1"*64,"acceptance_verifier_sha256":named["AcceptanceVerifierSha256"],"authority_public_key_sha256":"2"*64,"binding_sha256":"b"*64,"cas_provider_id":"provider","consumer_host_identity_sha256":"a"*64,"core_sha256":named["CoreSha256"],"desired_firewall":{},"python_sha256":"3"*64,"runner_sha256":named["RunnerSha256"],"source_host_identity_sha256":"d"*64,"ssh_keygen_sha256":"4"*64}
  task={"action":{"arguments":template["action"]["arguments"]["prefix"]+loader["encoded_command"],"execute":template["action"]["execute"],"working_directory":""},"action_count":1,"definition_xml_sha256":"f"*64,"principal":{"logon_type":"Interactive","run_level":"Highest","user_id":"host\\operator"},"settings":{"allow_demand_start":True,"disallow_start_on_batteries":False,"enabled":False,"execution_time_limit":"PT0S","hidden":False,"multiple_instances":"IgnoreNew","restart_count":0,"restart_interval":"PT0S","run_only_if_network_available":False,"start_when_available":False,"stop_on_batteries":False,"wake_to_run":False},"state":"Disabled","task_name":task_name,"task_path":"\\","trigger_count":0};payload={"component_id":{"finex-cas":"finex-trusted-utc-cas-responder-v1","finex-fetcher":"finex-trusted-utc-fetcher-v1","putra-producer":"putra-trusted-utc-producer-v1"}[role],"files":files,"firewall":None,"install_identity":"f"*64,"metadata":metadata,"schema_version":"finex-trusted-utc-installed-receipt-v1","task":task};receipt=install/"install-identity.sha256";receipt.write_bytes(canonical({"payload":payload,"payload_sha256":digest(json.dumps(payload,sort_keys=True,separators=(",",":")).encode()),"schema_version":"finex-trusted-utc-installed-receipt-envelope-v1"}))
  phase_role={"decoded_bindings":loader["decoded_bindings"],"encoded":loader["encoded_command"],"encoded_sha256":loader["encoded_command_sha256"],"generation_sha256":sha(graw),"plan_manifest_path":str((precommit/"precommit.json").resolve()),"plan_manifest_sha256":sha((precommit/"precommit.json").read_bytes()),"pointer_sha256":sha(praw),"public_key_fingerprint_sha256":public_fingerprint(pub),"signer_identity":signer,"task_template_sha256":sha(canonical(template))};request_role={"attestation_path":str(att.resolve()),"attestation_signature_path":str(Path(str(att.resolve())+".sig")),"config_and_key_bindings_json":str(bindings.resolve()),"firewall_json":str(firewall.resolve()),"installed_receipt_path":str(receipt.resolve()),"phase_b_public_key":str(pub.resolve()),"phase_b_signer_identity":signer};return phase_role,request_role
 def fixture(self,profile):
  self.case+=1;self.root=self.base/("case-"+str(self.case));self.root.mkdir()
  mapping={"finex":[("cas","finex-cas",1),("fetcher","finex-fetcher",2)],"putra":[("producer","putra-producer",1)]}[profile];phase={"binding_sha256":"b"*64,"consumer_host_identity_sha256":"a"*64,"expected_host_role":profile,"host_identity_sha256":("d"*64 if profile=="putra"else"a"*64),"release_identity_sha256":"c"*64,"release_inventory_sha256":"9"*64,"schema_version":profile+"-phase-d-phase-b-input-v3","source_host_identity_sha256":"d"*64};roles={}
  for short,role,index in mapping:phase[short],roles[short]=self.role(profile,short,role,index)
  phase_path=self.root/(profile+"-phase.json");phase_path.write_bytes(canonical(phase));request={"host_profile":profile,"output_path":str((self.root/(profile+"-post.json")).resolve()),"phase_b_inputs_json":str(phase_path.resolve()),"roles":roles,"schema_version":"finex-phase-d-installed-disabled-assembler-request-v1"};request_path=self.root/(profile+"-request.json");request_path.write_bytes(canonical(request));return request_path,request
 def test_real_crypto_finex_and_putra(self):
  for profile in("finex","putra"):
   with self.subTest(profile=profile):path,_=self.fixture(profile);self.assertEqual(assembler.build(path)["order_capability"],"DISABLED")
 def test_fake_receipt_and_post_activation_fields_rejected(self):
  path,request=self.fixture("putra");receipt=Path(request["roles"]["producer"]["installed_receipt_path"]);receipt.write_bytes(canonical({"schema_version":"test-installed-v1"}));self.assertRaises(assembler.AssembleError,assembler.build,path)
  path,request=self.fixture("finex");request["roles"]["cas"]["readiness_path"]=str(self.root/"not-ready");path.write_bytes(canonical(request));self.assertRaises(assembler.AssembleError,assembler.build,path)
  path,request=self.fixture("finex");request["roles"]["cas"]["attestation_path"]=request["roles"]["fetcher"]["attestation_path"];request["roles"]["cas"]["attestation_signature_path"]=request["roles"]["fetcher"]["attestation_signature_path"];path.write_bytes(canonical(request));self.assertRaises(assembler.AssembleError,assembler.build,path)
 def test_fake_verifier_key_substitution_and_trust_drift_rejected(self):
  path,request=self.fixture("putra");fake=self.root/"fake.cmd";marker=self.root/"marker";fake.write_text("@echo x>\""+str(marker)+"\"");request["ssh_keygen_path"]=str(fake);path.write_bytes(canonical(request));self.assertRaises(assembler.AssembleError,assembler.build,path);self.assertFalse(marker.exists())
  path,request=self.fixture("finex");request["roles"]["cas"]["phase_b_public_key"]=request["roles"]["fetcher"]["phase_b_public_key"];path.write_bytes(canonical(request));self.assertRaises(assembler.AssembleError,assembler.build,path)
  path,request=self.fixture("putra");phase=Path(request["phase_b_inputs_json"]);value=json.loads(phase.read_text());value["release_inventory_sha256"]="8"*64;phase.write_bytes(canonical(value));self.assertRaises(assembler.AssembleError,assembler.build,path)
 def test_reparse_input_rejected(self):
  path,request=self.fixture("putra");real=self.root/"real-link-target";real.mkdir();(real/"phase.json").write_bytes(Path(request["phase_b_inputs_json"]).read_bytes());link=self.root/"phase-junction";made=subprocess.run(["cmd.exe","/d","/c","mklink","/J",str(link),str(real)],capture_output=True)
  if made.returncode:self.skipTest("junction creation unavailable")
  try:request["phase_b_inputs_json"]=str(link/"phase.json");path.write_bytes(canonical(request));self.assertRaises(assembler.AssembleError,assembler.build,path)
  finally:subprocess.run(["cmd.exe","/d","/c","rmdir",str(link)],capture_output=True)
 def test_profiles_cover_all_loaded_release_scripts_without_repo_fallback(self):
  from operator_packs.finex_trusted_utc_phase_d_v1 import build_phase_d_unsigned_inputs as unsigned
  expected={"finex":{"OPERATOR_ENTRY_LOADER.ps1","STATUS_FINEX_PHASE_D.ps1","OPERATOR_PHASE_B.ps1","ACTIVATE_PHASE_B_V3_COMMON.ps1","ATTEST_PHASE_B_INSTALLED_DISABLED.ps1","PUBLISH_FINEX_TRUSTED_UTC_PHASE_C.ps1","INSTALL_FINEX_TRUSTED_UTC_CAS_RESPONDER.ps1","INSTALL_FINEX_TRUSTED_UTC_FETCHER.ps1","ACTIVATE_FINEX_TRUSTED_UTC_CAS_RESPONDER.ps1","ACTIVATE_FINEX_TRUSTED_UTC_FETCHER.ps1","APPLY_FINEX_TRUSTED_UTC_ACCEPTANCE.ps1"},"putra":{"OPERATOR_ENTRY_LOADER.ps1","OPERATOR_PHASE_B.ps1","ACTIVATE_PHASE_B_V3_COMMON.ps1","ATTEST_PHASE_B_INSTALLED_DISABLED.ps1","PUBLISH_FINEX_TRUSTED_UTC_PHASE_C.ps1","INSTALL_PUTRA_TRUSTED_UTC_PRODUCER.ps1","ACTIVATE_PUTRA_TRUSTED_UTC_PRODUCER.ps1"}}
  for profile,names in expected.items():
   for name in names:self.assertIn("v3/"+name,unsigned.PROFILES[profile]["required"])
  for script in("BUILD_FINEX_PHASE_D.ps1","PUTRA_PROVISION_PHASE_D.ps1"):
   text=(Path(assembler.__file__).parent/script).read_text();self.assertNotIn("$pack=Join-Path $repo 'operator_packs\\finex_trusted_utc_v1'",text);self.assertIn("PinPublished",text)
  finex=(Path(assembler.__file__).parent/"PREPARE_FINEX_PHASE_D_LOCAL.ps1").read_text();putra=(Path(assembler.__file__).parent/"PREPARE_PUTRA_PHASE_D_REMOTE.ps1").read_text()
  self.assertIn("if(-not$finalize){$ci=$phaseB.cas.decoded_bindings.runtime_invocation",finex);self.assertIn("'-AttestCasArgumentsJson',$tcp,'-AttestFetcherArgumentsJson',$tfp",finex)
  self.assertIn("if(-not$finalize){$pi=$phaseB.producer.decoded_bindings.runtime_invocation",putra);self.assertIn("'-AttestArgumentsJson',$preAttestPath",putra)
  self.assertNotIn("$post.producer.readiness_path",putra);self.assertNotIn("$post.cas.readiness_path",finex)
if __name__=="__main__":unittest.main()
