import hashlib,json,subprocess,sys,tempfile,unittest
from pathlib import Path
from operator_packs.finex_trusted_utc_phase_d_v1 import build_phase_b_v3_requests as requests
from operator_packs.finex_trusted_utc_phase_d_v1 import build_phase_d_unsigned_inputs as unsigned
from operator_packs.finex_trusted_utc_phase_d_v1 import generate_phase_b_v3_precommit as generator
from test_phase_b_v3_precommit_generator import GeneratorIntegrationTests,PACK,PREPARE,hf,canon

ROOT=Path(__file__).resolve().parent;BUILD=ROOT/"operator_packs/finex_trusted_utc_phase_d_v1/BUILD_FINEX_PHASE_D.ps1"
class ProductionRequestBuilderTests(unittest.TestCase):
 def setUp(self):
  self.base=GeneratorIntegrationTests("test_real_all_roles_and_prepare_phase_b_inputs");self.base.setUp();self.extra=tempfile.TemporaryDirectory();self.root=Path(self.extra.name);self.counter=0
 def tearDown(self):
  if self.root.exists():generator.core.unseal_directory_for_cleanup(self.root)
  self.extra.cleanup();self.base.tearDown()
 def make_profile(self,profile,tag):
  published=self.root/(tag+"-published");builder_root=self.root/(tag+"-builder");source_root=self.root/(tag+"-sources");roles=("finex-cas","finex-fetcher") if profile=="finex" else("putra-producer",);joint=json.loads(self.base.binding.read_bytes())["payload"]
  required=unsigned.PROFILES[profile]["required"];artifacts=[];raws={}
  for rel in sorted(required):
   name=Path(rel).name;actual=ROOT/"operator_packs/finex_trusted_utc_v1"/name
   if rel=="configs/public_keys/putra_authority.pub":raw=Path(str(self.base.keys["putra"])+".pub").read_bytes()
   elif rel=="configs/public_keys/finex_acceptance.pub":raw=Path(str(self.base.keys["finex"])+".pub").read_bytes()
   elif actual.is_file():raw=actual.read_bytes()
   else:raw=("dependency:"+rel).encode()
   source=source_root/rel;source.parent.mkdir(parents=True,exist_ok=True);source.write_bytes(raw);raws[rel]=raw;artifacts.append({"relative_path":rel,"sha256":hashlib.sha256(raw).hexdigest(),"source_path":str(source.resolve())})
  absolute=str((self.root/profile/"runtime-item").resolve());acl={"protected_paths":[absolute],"records":[{"aces":[],"dacl_protected":True,"dacl_sha256":"1"*64,"file_identity":[1,2],"owner_sid":"S-1-5-18","path":absolute,"resolved_path":absolute,"role":"leaf"}],"schema_version":"finex-runtime-acl-policy-v1"};generated=[{"kind":"acl_policy","relative_path":"policies/runtime_acl_policy.json","value":acl}]
  if profile=="finex":config={"acceptance_custody_issuer_id":"issuer","acceptance_custody_key_id":"key","acceptance_private_key_path":absolute,"acceptance_public_key_file_sha256":"1"*64,"acceptance_public_key_path":absolute,"acceptance_public_key_sha256":"2"*64,"clock_binding_sha256":json.loads(self.base.binding.read_bytes())["binding_sha256"],"consumer_host_identity_sha256":joint["consumer_host_identity_sha256"],"custody_issuer_id":"issuer","custody_key_fingerprint_sha256":"3"*64,"custody_key_id":"key","database_path":absolute,"hmac_key_path":absolute,"poll_interval_ms":250,"provider_id":joint["cas_provider_id"],"request_directory":absolute,"response_directory":absolute,"schema_version":"windows-trusted-utc-continuity-cas-responder-v1","source_host_identity_sha256":joint["source_host_identity_sha256"],"ssh_keygen_path":absolute,"ssh_keygen_sha256":"4"*64};generated.append({"kind":"cas_config","relative_path":"configs/cas-responder.json","value":config})
  else:config={"acceptance_custody_issuer_id":joint["acceptance_custody_issuer_id"],"acceptance_custody_key_id":joint["acceptance_custody_key_id"],"allowed_remote_ip":"100.80.180.13","bind_ip":"100.121.177.7","binding_sha256":json.loads(self.base.binding.read_bytes())["binding_sha256"],"cas_provider_id":joint["cas_provider_id"],"consumer_host_identity_sha256":joint["consumer_host_identity_sha256"],"port":43130,"readiness_private_key_path":str(self.base.keys["producer-ready"].resolve()),"schema_version":"putra-trusted-utc-producer-prepared-config-v1","source_host_identity_sha256":joint["source_host_identity_sha256"]};generated.append({"kind":"producer_config","relative_path":"configs/producer.json","value":config})
  for role in roles:
   authority=self.base.keys["putra" if role=="putra-producer" else"finex"];ready=self.base.keys[{"finex-cas":"cas-ready","finex-fetcher":"fetch-ready","putra-producer":"producer-ready"}[role]];local_raw=Path(str(authority)+".pub").read_bytes();ready_raw=Path(str(ready)+".pub").read_bytes()
   if role=="finex-cas":pins={"acceptance_core_sha256":hashlib.sha256(raws["dependencies/live_runtime/windows_trusted_utc_continuity_acceptance.py"]).hexdigest(),"config_sha256":hashlib.sha256(canon(config)).hexdigest(),"operator_core_sha256":hashlib.sha256(raws["v3/finex_trusted_utc.py"]).hexdigest(),"responder_core_sha256":hashlib.sha256(raws["dependencies/live_runtime/windows_trusted_utc_continuity_cas_responder.py"]).hexdigest()}
   elif role=="finex-fetcher":peer=raws["configs/public_keys/putra_authority.pub"];pins={"response_authority_public_key_file_sha256":hashlib.sha256(peer).hexdigest(),"response_authority_public_key_sha256":unsigned.ssh_fingerprint(peer)}
   else:peer=raws["configs/public_keys/finex_acceptance.pub"];pins={"acceptance_custody_issuer_id":joint["acceptance_custody_issuer_id"],"acceptance_custody_key_id":joint["acceptance_custody_key_id"],"acceptance_public_key_file_sha256":hashlib.sha256(peer).hexdigest(),"acceptance_public_key_sha256":unsigned.ssh_fingerprint(peer),"acceptance_verifier_sha256":hashlib.sha256(raws["dependencies/live_runtime/windows_trusted_utc_continuity_acceptance.py"]).hexdigest(),"authority_public_key_sha256":self.base._fp(authority),"cas_provider_id":joint["cas_provider_id"]}
   descriptor={"binding_sha256":json.loads(self.base.binding.read_bytes())["binding_sha256"],"consumer_host_identity_sha256":joint["consumer_host_identity_sha256"],"local_signing_authority_public_key_file_sha256":hashlib.sha256(local_raw).hexdigest(),"local_signing_authority_public_key_sha256":self.base._fp(authority),"operator_role":role,"readiness_public_key_file_sha256":hashlib.sha256(ready_raw).hexdigest(),"readiness_public_key_sha256":self.base._fp(ready),"runtime_pins":pins,"schema_version":"finex-phase-b-config-and-key-bindings-v1","source_host_identity_sha256":joint["source_host_identity_sha256"]};generated.extend([{"kind":role.replace("-","_")+"_bindings" if role!="putra-producer" else"producer_bindings","relative_path":"configs/"+role+"-config-and-key-bindings.json","value":descriptor},{"kind":role.replace("-","_")+"_firewall" if role!="putra-producer" else"producer_firewall","relative_path":"configs/"+role+"-firewall.json","value":{"display_name":"AI_SCALPER FINEX Trusted UTC Producer V1"if role=="putra-producer"else"AI_SCALPER_FINEX_TRUSTED_UTC_V1","phase":"absent","schema_version":"finex-phase-b-firewall-topology-v3"}}])
  unsigned_request=self.root/(tag+"-unsigned-request.json");unsigned_request.write_bytes(unsigned.canonical({"artifacts":artifacts,"generated":generated,"output_root":str(builder_root.resolve()),"profile":profile,"schema_version":"finex-phase-d-unsigned-input-request-v1"}));result=unsigned.build(unsigned_request);q=lambda v:"'"+str(v).replace("'","''")+"'";command="& "+q(BUILD)+" -RepoRoot "+q(ROOT)+" -OutputRoot "+q(published)+" -PublishUnsigned -UnsignedArtifactsManifestJson "+q(result["manifest_path"])+" -BuilderRequestJson "+q(unsigned_request)+" -ExpectedUnsignedProfile "+profile;run=subprocess.run([str(self.base.power),"-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-Command",command],capture_output=True,text=True,timeout=30);self.assertEqual(0,run.returncode,run.stdout+run.stderr)
  return published,roles
 def build_requests(self,profile):
  self.counter+=1;tag=profile+"-"+str(self.counter);published,roles=self.make_profile(profile,tag);state=(self.root/(tag+"-state")).resolve();output=(self.root/(tag+"-requests")).resolve();local=self.base.keys["finex"if profile=="finex"else"putra"];peer=published/("configs/public_keys/putra_authority.pub"if profile=="finex"else"configs/public_keys/finex_acceptance.pub");readiness={role:{"private_key_path":str(self.base.keys[{"finex-cas":"cas-ready","finex-fetcher":"fetch-ready","putra-producer":"producer-ready"}[role]].resolve()),"public_key_path":str(Path(str(self.base.keys[{"finex-cas":"cas-ready","finex-fetcher":"fetch-ready","putra-producer":"producer-ready"}[role]])+".pub").resolve())}for role in roles};operational={"finex-cas":{},"finex-fetcher":{"allowed_remote_ip":"100.121.177.7","cadence_seconds":2,"url":"http://100.121.177.7:43130/v1/trusted-utc"},"putra-producer":{"allowed_remote_ip":"100.80.180.13","bind_ip":"100.121.177.7","port":43130}};value={"action_execute_path":str(self.base.power.resolve()),"finex_host_identity_path":str(self.base.hosts["finex"][0].resolve()),"finex_host_identity_signature_path":str(self.base.hosts["finex"][1].resolve()),"finex_joint_binding_signature_path":str(self.base.joint_sigs["finex"].resolve()),"generation_ids":{role:str(index+1)*32 for index,role in enumerate(roles)},"host_profile":profile,"joint_binding_path":str(self.base.binding.resolve()),"local_signing_private_key_path":str(local.resolve()),"operational":{role:operational[role]for role in roles},"output_root":str(output),"peer_authority_public_key_path":str(peer.resolve()),"published_root":str(published.resolve()),"putra_host_identity_path":str(self.base.hosts["putra"][0].resolve()),"putra_host_identity_signature_path":str(self.base.hosts["putra"][1].resolve()),"putra_joint_binding_signature_path":str(self.base.joint_sigs["putra"].resolve()),"python_path":str(Path(sys.executable).resolve()),"readiness":readiness,"release_identity_path":str(self.base.release_path.resolve()),"runtime_state_root":str(state),"schema_version":"finex-phase-b-v3-production-request-input-v1","ssh_keygen_path":str(self.base.ssh.resolve()),"task_user_id":"HOST\\operator"};path=self.root/(tag+"-production-input.json");path.write_bytes(requests.canonical(value));return path,value,roles
 def test_builds_exact_requests_and_generates_all_roles(self):
  for profile in("finex","putra"):
   path,value,roles=self.build_requests(profile);result=requests.build(path);self.assertEqual(set(roles),set(result["requests"]));roots={}
   for role in roles:
    self.assertEqual(role,generator.generate(Path(result["requests"][role]))["operator_role"]);roots[role]=Path(json.loads(Path(result["requests"][role]).read_bytes())["precommit_root"])
   key=self.base.keys["finex"if profile=="finex"else"putra"];evidence,sig,fp=self.base._evidence(profile,key);handoff_path=self.root/(profile+"-production-phase-b-input.json");command=[sys.executable,str(PREPARE),"--host-role",profile,"--ssh-keygen",str(self.base.ssh),"--public-key",str(key)+".pub","--expected-public-fingerprint",fp,"--signer-identity",profile+"-phase-d-operator","--key-evidence",str(evidence),"--key-evidence-signature",str(sig),"--host-identity",str(self.base.hosts[profile][0]),"--joint-binding",str(self.base.binding),"--output",str(handoff_path)]
   for role in roles:command.extend(["--"+{"finex-cas":"cas","finex-fetcher":"fetcher","putra-producer":"producer"}[role]+"-precommit",str(roots[role])])
   assembled=subprocess.run(command,capture_output=True,text=True,timeout=30,check=False);self.assertEqual(0,assembled.returncode,assembled.stdout+assembled.stderr);handoff=json.loads(handoff_path.read_bytes());finalize=[];published=Path(value["published_root"])
   for role in roles:
    short={"finex-cas":"cas","finex-fetcher":"fetcher","putra-producer":"producer"}[role];materialized=self.root/(profile+"-"+short+"-materialized.json");materialized.write_bytes(canon({"decoded_bindings":handoff[short]["decoded_bindings"],"encoded_command":handoff[short]["encoded"],"encoded_command_sha256":handoff[short]["encoded_sha256"],"schema_version":"finex-phase-b-materialized-loader-v3"}));argument=self.root/(profile+"-"+short+"-finalize.json");argument.write_bytes(canon({"PhaseBMaterializedLoaderJson":str(materialized.resolve()),"PhaseBPublicKeyPath":str(Path(str(key)+".pub").resolve()),"PhaseBPublicKeySha256":hf(str(key)+".pub"),"PhaseBSignerIdentity":profile+"-phase-d-operator","PhaseBSshKeygenPath":str(self.base.ssh.resolve()),"PhaseBSshKeygenSha256":hf(self.base.ssh),"PrecommitRoot":str(roots[role].resolve()),"PythonPath":str(Path(sys.executable).resolve()),"PythonSha256":hf(sys.executable),"V3CorePath":str((published/"v3/phase_b_asymmetric_v3.py").resolve()),"V3CoreSha256":hf(published/"v3/phase_b_asymmetric_v3.py")}));finalize.append(argument)
   q=lambda item:"'"+str(item).replace("'","''")+"'";expected="@('finex-cas','finex-fetcher')"if profile=="finex"else"@('putra-producer')";arguments="@("+",".join(q(item)for item in finalize)+")";trusted=" -TrustedFinalizePythonPath "+q(Path(sys.executable).resolve())+" -TrustedFinalizePythonSha256 "+hf(sys.executable);base_command="& "+q(BUILD)+" -RepoRoot "+q(ROOT)+" -OutputRoot "+q(self.root)+" -PublishedReleaseRoot "+q(published)+" -FinalizePublished -UnsignedContentManifestPath "+q(published/"unsigned_content_manifest.json")+" -ExpectedFinalizeRoles "+expected
   policy_environment=self.base._finalize_policy_env(key)
   if profile=="finex":
    marker=self.root/"fake-finalize-python-executed";fake=self.root/"fake-finalize-python.cmd";fake.write_text("@echo off\r\necho executed>\""+str(marker)+"\"\r\n",encoding="ascii");source_argument=json.loads(finalize[0].read_bytes());source_materialized=json.loads(Path(source_argument["PhaseBMaterializedLoaderJson"]).read_bytes());source_materialized["decoded_bindings"]["operator_role"]="putra-producer";forged_materialized=self.root/"forged-materialized.json";forged_materialized.write_bytes(canon(source_materialized));source_argument["PhaseBMaterializedLoaderJson"]=str(forged_materialized.resolve());source_argument["PythonPath"]=str(fake.resolve());source_argument["PythonSha256"]=hf(fake);forged_argument=self.root/"forged-finalize-argument.json";forged_argument.write_bytes(canon(source_argument));attack_arguments="@("+",".join(q(item)for item in [forged_argument,*finalize[1:]])+")";fake_trusted=" -TrustedFinalizePythonPath "+q(fake.resolve())+" -TrustedFinalizePythonSha256 "+hf(fake);attack=subprocess.run([str(self.base.power),"-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-Command",base_command+" -FinalizeArgumentsJson "+attack_arguments+fake_trusted],capture_output=True,text=True,timeout=30,check=False,env=policy_environment);self.assertNotEqual(0,attack.returncode);self.assertIn("PHASE_D_FINALIZE_CALLER_PYTHON_MISMATCH",attack.stdout+attack.stderr);self.assertFalse(marker.exists())
   finalize_command=base_command+" -FinalizeArgumentsJson "+arguments+trusted;finalized=subprocess.run([str(self.base.power),"-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-Command",finalize_command],capture_output=True,text=True,timeout=30,check=False,env=policy_environment);self.assertEqual(0,finalized.returncode,finalized.stdout+finalized.stderr);self.assertIn("FINALIZED_WITHOUT_RELEASE_MUTATION",finalized.stdout)
 def test_wrong_peer_extra_field_pointer_and_noncanonical_fail(self):
  path,value,roles=self.build_requests("finex");value["peer_authority_public_key_path"]=str(Path(str(self.base.keys["finex"])+".pub").resolve());path.write_bytes(requests.canonical(value));self.assertRaises(requests.RequestBuildError,requests.build,path)
  path,value,roles=self.build_requests("putra");value["extra"]=True;path.write_bytes(requests.canonical(value));self.assertRaises(requests.RequestBuildError,requests.build,path)
  path,value,roles=self.build_requests("finex");state=Path(value["runtime_state_root"]);state.mkdir();(state/(roles[0]+"-current.json")).write_text("x");self.assertRaises(requests.RequestBuildError,requests.build,path)
  path,value,roles=self.build_requests("putra");path.write_bytes(path.read_bytes()+b" ");self.assertRaises(requests.RequestBuildError,requests.build,path)
 def test_published_peer_key_hash_drift_is_rejected(self):
  path,value,_=self.build_requests("finex");published=Path(value["published_root"]);generator.core.unseal_directory_for_cleanup(published);Path(value["peer_authority_public_key_path"]).write_bytes(Path(str(self.base.keys["finex"])+".pub").read_bytes())
  with self.assertRaisesRegex(requests.RequestBuildError,"PHASE_B_REQUEST_INVENTORY_DRIFT"):requests.build(path)
if __name__=="__main__":unittest.main()
