Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
function Invoke-PhaseBV3Activation([string]$TaskName,[string]$TaskPath,[string]$PrecommitRoot,[string]$AttestationPath,[string]$AttestationSignaturePath,[string]$PythonPath,[string]$V3CorePath,[string]$SshKeygenPath,[string]$PublicKeyPath,[string]$SignerIdentity,[string]$FirewallJson,[string]$ConfigAndKeyBindingsJson,[string]$ReadinessReceiptPath,[string]$ReadinessPublicKeyPath,[string]$ReadinessSignerIdentity,[string]$WindowsObserverPath,[string]$WindowsObserverSha256,[string]$ActiveFirewallJson=''){
 if(-not('PhaseBV3ActivationAncestorNative'-as[type])){Add-Type -TypeDefinition 'using System;using System.Runtime.InteropServices;public static class PhaseBV3ActivationAncestorNative{[DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)]public static extern IntPtr CreateFileW(string n,uint a,uint s,IntPtr x,uint c,uint f,IntPtr t);}' }
 function AH([string]$Path,[string]$Reason){$full=[IO.Path]::GetFullPath([IO.Path]::GetDirectoryName($Path));$root=[IO.Path]::GetPathRoot($full);$targets=[Collections.Generic.List[string]]::new();$targets.Add($root);$cursor=$root;foreach($part in $full.Substring($root.Length).Split([IO.Path]::DirectorySeparatorChar,[StringSplitOptions]::RemoveEmptyEntries)){$cursor=Join-Path $cursor $part;$targets.Add($cursor)};$result=[Collections.Generic.List[Microsoft.Win32.SafeHandles.SafeFileHandle]]::new();try{foreach($target in $targets){$item=Get-Item -LiteralPath $target -Force -ErrorAction Stop;if(-not$item.PSIsContainer-or($item.Attributes-band[IO.FileAttributes]::ReparsePoint)){throw$Reason};$raw=[PhaseBV3ActivationAncestorNative]::CreateFileW($target,0x00100080,3,[IntPtr]::Zero,3,0x02000000,[IntPtr]::Zero);if($raw-eq[System.IntPtr]::new(-1)){$error=[Runtime.InteropServices.Marshal]::GetLastWin32Error();if($error-eq5){$raw=[PhaseBV3ActivationAncestorNative]::CreateFileW($target,0,3,[IntPtr]::Zero,3,0x02000000,[IntPtr]::Zero)};if($raw-eq[System.IntPtr]::new(-1)){throw$Reason}};$result.Add([Microsoft.Win32.SafeHandles.SafeFileHandle]::new($raw,$true))};return,$result.ToArray()}catch{foreach($handle in $result){$handle.Dispose()};throw}}
 function HASHB([byte[]]$Bytes){$h=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($h.ComputeHash($Bytes)).Replace('-','').ToLowerInvariant())}finally{$h.Dispose()}}
 function HOLD([string]$Path,[string]$Sha256,[string]$Reason){if(-not[IO.Path]::IsPathRooted($Path)){throw$Reason};$full=[IO.Path]::GetFullPath($Path);$ancestors=@(AH $full $Reason);$resolved=(Resolve-Path -LiteralPath $Path).Path;if($full-cne$resolved){foreach($a in $ancestors){$a.Dispose()};throw$Reason};$chain=Get-Item -LiteralPath $resolved -Force;while($null-ne$chain){if($chain.Attributes-band[IO.FileAttributes]::ReparsePoint){foreach($a in $ancestors){$a.Dispose()};throw$Reason};$chain=if($chain-is[IO.DirectoryInfo]){$chain.Parent}else{$chain.Directory}};$s=[IO.File]::Open($resolved,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);try{$m=[IO.MemoryStream]::new();$s.CopyTo($m);$b=$m.ToArray();$m.Dispose();$s.Position=0;$h=[Security.Cryptography.SHA256]::Create();try{$actual=([BitConverter]::ToString($h.ComputeHash($b)).Replace('-','').ToLowerInvariant())}finally{$h.Dispose()};if($actual-cne$Sha256){throw $Reason};[pscustomobject]@{Stream=$s;Bytes=$b;Ancestors=$ancestors}}catch{$s.Dispose();foreach($a in $ancestors){$a.Dispose()};throw}}
 function HOLDRAW([string]$Path,[string]$Reason){if(-not[IO.Path]::IsPathRooted($Path)){throw$Reason};$full=[IO.Path]::GetFullPath($Path);$ancestors=@(AH $full $Reason);$resolved=(Resolve-Path -LiteralPath $Path).Path;if($full-cne$resolved){foreach($a in $ancestors){$a.Dispose()};throw$Reason};$chain=Get-Item -LiteralPath $resolved -Force;while($null-ne$chain){if($chain.Attributes-band[IO.FileAttributes]::ReparsePoint){foreach($a in $ancestors){$a.Dispose()};throw$Reason};$chain=if($chain-is[IO.DirectoryInfo]){$chain.Parent}else{$chain.Directory}};$s=[IO.File]::Open($resolved,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);try{$m=[IO.MemoryStream]::new();$s.CopyTo($m);$b=$m.ToArray();$m.Dispose();$s.Position=0;[pscustomobject]@{Stream=$s;Bytes=$b;Path=$full;Hash=(HASHB $b);Ancestors=$ancestors}}catch{$s.Dispose();foreach($a in $ancestors){$a.Dispose()};throw}}
 function HOLDCHAIN($Bindings,$Collection){$base=[IO.Path]::GetFullPath([string]$Bindings.future_pointer_path);$path=$base;$last=[int]$Bindings.sequence;if($last-lt1-or$last-gt100000){throw 'PHASE_B_V3_CHAIN_SEQUENCE_INVALID'};for($seq=1;$seq-le$last;$seq++){$pointer=HOLDRAW $path 'PHASE_B_V3_CHAIN_POINTER_INVALID';$Collection.Add($pointer);$envelope=[Text.Encoding]::UTF8.GetString($pointer.Bytes)|ConvertFrom-Json -ErrorAction Stop;if([int]$envelope.payload.sequence-ne$seq){throw 'PHASE_B_V3_CHAIN_SEQUENCE_MISMATCH'};$generationId=[string]$envelope.payload.generation_id;if([string]::IsNullOrWhiteSpace($generationId)){throw 'PHASE_B_V3_CHAIN_GENERATION_ID_MISSING'};$generationPath=Join-Path ($base+'.generations') ($generationId+'.generation-bundle-v3.json');$generation=HOLDRAW $generationPath 'PHASE_B_V3_CHAIN_GENERATION_INVALID';$Collection.Add($generation);if($seq-eq$last){if($pointer.Hash-cne[string]$Bindings.future_pointer_sha256){throw 'PHASE_B_V3_FINAL_POINTER_HASH_MISMATCH'};if($generationId-cne[string]$Bindings.generation_id){throw 'PHASE_B_V3_FINAL_GENERATION_ID_MISMATCH'}}else{$path=Join-Path ($base+'.successors') ($pointer.Hash+'.json')}}}
 function CORE([string[]]$Arguments){$encoded=[Convert]::ToBase64String($core.Bytes);$bootstrap="import base64,sys;src=base64.b64decode('$encoded');sys.argv=[sys.argv[1]]+sys.argv[2:];g={'__name__':'__main__','__file__':sys.argv[0]};exec(compile(src,sys.argv[0],'exec'),g,g)";& $PythonPath -I -B -c $bootstrap @Arguments;if($LASTEXITCODE-ne0){throw 'PHASE_B_V3_PINNED_CORE_FAILED'}}
 $holds=[Collections.Generic.List[object]]::new();$temporary=[IO.Path]::GetTempFileName();$firewallCreated=$false;$challengeCreated=$false
 try{
  $observer=HOLD $WindowsObserverPath $WindowsObserverSha256 'WINDOWS_OBSERVER_IDENTITY_MISMATCH';$holds.Add($observer);. ([ScriptBlock]::Create([Text.Encoding]::UTF8.GetString($observer.Bytes)));$installedFirewall=Get-Content -Raw -LiteralPath $FirewallJson|ConvertFrom-Json;$activeFirewall=if([string]::IsNullOrWhiteSpace($ActiveFirewallJson)){$installedFirewall}else{Get-Content -Raw -LiteralPath $ActiveFirewallJson|ConvertFrom-Json};$configBindings=Get-Content -Raw -LiteralPath $ConfigAndKeyBindingsJson|ConvertFrom-Json
  $live=Get-PhaseBV3WindowsTopology $TaskName $TaskPath $installedFirewall $configBindings;if($live.state-cne'Disabled'-or$live.trigger_count-ne0-or(Test-Path -LiteralPath $ReadinessReceiptPath)){throw 'PHASE_B_V3_ACTIVATION_PRECONDITION_INVALID'}
  $encodedMatch=[regex]::Match([string]$live.action.arguments,'-EncodedCommand ([A-Za-z0-9+/=]+)$');if(-not$encodedMatch.Success){throw 'PHASE_B_V3_TASK_LOADER_INVALID'};$loader=Get-PhaseBV3EncodedLoaderBindings $encodedMatch.Groups[1].Value;$invocation=$loader.runtime_invocation
  if($invocation.python_path-cne[IO.Path]::GetFullPath($PythonPath)-or$invocation.v3_core_path-cne[IO.Path]::GetFullPath($V3CorePath)-or$invocation.ssh_keygen_path-cne[IO.Path]::GetFullPath($SshKeygenPath)-or$invocation.public_key_path-cne[IO.Path]::GetFullPath($PublicKeyPath)){throw 'PHASE_B_V3_ACTIVATION_DEPENDENCY_BINDING_INVALID'}
  foreach($spec in @(@($PythonPath,$invocation.python_sha256,'PYTHON_IDENTITY_MISMATCH'),@($V3CorePath,$invocation.v3_core_sha256,'V3_CORE_IDENTITY_MISMATCH'),@($SshKeygenPath,$invocation.ssh_keygen_sha256,'SSH_KEYGEN_IDENTITY_MISMATCH'),@($PublicKeyPath,$invocation.public_key_file_sha256,'PUBLIC_KEY_IDENTITY_MISMATCH'))){$held=HOLD $spec[0] $spec[1] $spec[2];$holds.Add($held)}
  $python=$holds[$holds.Count-4];$core=$holds[$holds.Count-3];HOLDCHAIN $loader $holds;Write-PhaseBV3CanonicalJson $live $temporary;CORE -Arguments @($V3CorePath,'verify-activation','--precommit',$PrecommitRoot,'--live-topology',$temporary,'--public-key',$PublicKeyPath,'--signer-identity',$SignerIdentity,'--ssh-keygen',$SshKeygenPath,'--attestation',$AttestationPath,'--attestation-signature',$AttestationSignaturePath,'--output',($temporary+'.verified'))
  $named=$invocation.runtime_arguments.named;foreach($required in @('ReadinessChallengePath','ReadinessReceiptPath','ReadinessRole')){if($named.PSObject.Properties.Name-cnotcontains$required){throw 'READINESS_RUNTIME_BINDING_INCOMPLETE'}};if([IO.Path]::GetFullPath([string]$named.ReadinessReceiptPath)-cne[IO.Path]::GetFullPath($ReadinessReceiptPath)){throw 'READINESS_RUNTIME_BINDING_INCOMPLETE'}
  $baselineRevision=0;$baselineHead='0'*64;if($named.PSObject.Properties.Name-ccontains'SuccessEvidencePath'){foreach($required in @('OperatorCorePath','OperatorCoreSha256','RuntimeAclPolicyPath','RuntimeAclPolicySha256','ConfigPath','ConfigSha256')){if($named.PSObject.Properties.Name-cnotcontains$required){throw 'CAS_BASELINE_RUNTIME_BINDING_INCOMPLETE'}};$held=HOLD $named.OperatorCorePath $named.OperatorCoreSha256 'OPERATOR_CORE_IDENTITY_MISMATCH';$holds.Add($held);$baselineOutput=@(& $PythonPath $named.OperatorCorePath --runtime-acl-policy-path $named.RuntimeAclPolicyPath --runtime-acl-policy-sha256 $named.RuntimeAclPolicySha256 snapshot-cas-baseline --config-path $named.ConfigPath --config-sha256 $named.ConfigSha256);if($LASTEXITCODE-ne0-or$baselineOutput.Count-ne1){throw 'CAS_LIVE_BASELINE_FAILED'};$baseline=$baselineOutput[0]|ConvertFrom-Json;$baselineRevision=[int]$baseline.revision;$baselineHead=[string]$baseline.head_sha256}
  $challengePath=[IO.Path]::GetFullPath([string]$named.ReadinessChallengePath);if(Test-Path -LiteralPath $challengePath){throw 'READINESS_CHALLENGE_COLLISION'};[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($challengePath))|Out-Null;$nonceBytes=[byte[]]::new(32);[Security.Cryptography.RandomNumberGenerator]::Fill($nonceBytes);$nonce=([BitConverter]::ToString($nonceBytes).Replace('-','').ToLowerInvariant());$now=[DateTime]::UtcNow;$challenge=[ordered]@{baseline_head_sha256=$baselineHead;baseline_revision=$baselineRevision;deadline_utc=$now.AddSeconds(45).ToString('yyyy-MM-ddTHH:mm:ss.ffffffZ',[Globalization.CultureInfo]::InvariantCulture);generation_id=[string]$loader.generation_id;issued_at_utc=$now.ToString('yyyy-MM-ddTHH:mm:ss.ffffffZ',[Globalization.CultureInfo]::InvariantCulture);nonce=$nonce;pointer_sha256=[string]$loader.future_pointer_sha256;role=[string]$named.ReadinessRole;schema_version='finex-role-readiness-challenge-v3';task_name=$TaskName};Write-PhaseBV3CanonicalJson $challenge $challengePath;$challengeCreated=$true
  $preMutation=Get-PhaseBV3WindowsTopology $TaskName $TaskPath $installedFirewall $configBindings;if(($preMutation|ConvertTo-Json -Depth 60 -Compress)-cne($live|ConvertTo-Json -Depth 60 -Compress)){throw 'PHASE_B_V3_ACTIVATION_TOPOLOGY_TOCTOU'}
  if(-not[string]::IsNullOrWhiteSpace($ActiveFirewallJson)){if($activeFirewall.schema_version-cne'finex-phase-b-firewall-topology-v3'-or$activeFirewall.phase-cne'active'-or(Get-NetFirewallRule -DisplayName $activeFirewall.display_name -ErrorAction SilentlyContinue)){throw 'FIREWALL_RESOURCE_COLLISION'};New-NetFirewallRule -DisplayName $activeFirewall.display_name -Direction $activeFirewall.direction -Action $activeFirewall.action -Protocol $activeFirewall.protocol -LocalPort $activeFirewall.local_port -LocalAddress $activeFirewall.local_address -RemoteAddress $activeFirewall.remote_address -Profile $activeFirewall.profile|Out-Null;$firewallCreated=$true}
  Enable-ScheduledTask -TaskName $TaskName -TaskPath $TaskPath|Out-Null;Start-ScheduledTask -TaskName $TaskName -TaskPath $TaskPath;$deadline=[DateTime]::UtcNow.AddSeconds(45);while(-not(Test-Path -LiteralPath $ReadinessReceiptPath)-and[DateTime]::UtcNow-lt$deadline){if([string](Get-ScheduledTask -TaskName $TaskName -TaskPath $TaskPath).State-cne'Running'){throw 'TASK_EXITED_BEFORE_SIGNED_READINESS'};Start-Sleep -Milliseconds 100};if(-not(Test-Path -LiteralPath $ReadinessReceiptPath)){throw 'PHASE_B_V3_READINESS_TIMEOUT'}
  $running=Get-PhaseBV3WindowsTopology $TaskName $TaskPath $activeFirewall $configBindings;Write-PhaseBV3CanonicalJson $running $temporary;CORE -Arguments @($V3CorePath,'verify-runtime-readiness','--precommit',$PrecommitRoot,'--live-topology',$temporary,'--public-key',$PublicKeyPath,'--signer-identity',$SignerIdentity,'--ssh-keygen',$SshKeygenPath,'--attestation',$AttestationPath,'--attestation-signature',$AttestationSignaturePath,'--readiness',$ReadinessReceiptPath,'--readiness-public-key',$ReadinessPublicKeyPath,'--readiness-identity',$ReadinessSignerIdentity)
 }catch{Stop-ScheduledTask -TaskName $TaskName -TaskPath $TaskPath -ErrorAction SilentlyContinue;Disable-ScheduledTask -TaskName $TaskName -TaskPath $TaskPath -ErrorAction SilentlyContinue|Out-Null;if($firewallCreated){Remove-NetFirewallRule -DisplayName $activeFirewall.display_name -ErrorAction SilentlyContinue};if($challengeCreated){Remove-Item -LiteralPath $challengePath -Force -ErrorAction SilentlyContinue};throw}finally{Remove-Item -LiteralPath $temporary,($temporary+'.verified') -Force -ErrorAction SilentlyContinue;foreach($held in $holds){$held.Stream.Dispose();foreach($ancestor in @($held.Ancestors)){$ancestor.Dispose()}}}
}
