# EXTERNAL_PRETRUST_LOADER_REQUIRED: common v3 activation consumes held, hash-pinned bytes.
# TASK_ACTION_IDENTITY_MISMATCH: common v3 structural verifier enforces this failure.
# EXPLICIT_ACTIVATE_SWITCH_REQUIRED: compatibility name; v3 gate remains mandatory.
[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param([Parameter(Mandatory=$true)][string]$PrecommitRoot,[Parameter(Mandatory=$true)][string]$AttestationPath,[Parameter(Mandatory=$true)][string]$AttestationSignaturePath,[Parameter(Mandatory=$true)][string]$PythonPath,[Parameter(Mandatory=$true)][string]$V3CorePath,[Parameter(Mandatory=$true)][string]$SshKeygenPath,[Parameter(Mandatory=$true)][string]$PublicKeyPath,[Parameter(Mandatory=$true)][ValidateSet('finex-phase-d-operator','putra-phase-d-operator')][string]$SignerIdentity,[Parameter(Mandatory=$true)][string]$FirewallJson,[Parameter(Mandatory=$true)][string]$ConfigAndKeyBindingsJson,[Parameter(Mandatory=$true)][string]$ReadinessReceiptPath,[Parameter(Mandatory=$true)][string]$ReadinessPublicKeyPath,[Parameter(Mandatory=$true)][string]$ReadinessSignerIdentity,[Parameter(Mandatory=$true)][string]$ActivationCommonPath,[Parameter(Mandatory=$true)][string]$ActivationCommonSha256,[Parameter(Mandatory=$true)][string]$WindowsObserverPath,[Parameter(Mandatory=$true)][string]$WindowsObserverSha256,[switch]$Activate)
$ErrorActionPreference='Stop';if(-not$Activate){throw 'PHASE_B_V3_EXPLICIT_ACTIVATE_REQUIRED'};$OperatorRole='finex-fetcher';$TaskName='AI_SCALPER_FINEX_TRUSTED_UTC_FETCHER_V1';if(($OperatorRole-eq'putra-producer')-ne($SignerIdentity-eq'putra-phase-d-operator')){throw 'PHASE_B_V3_SIGNER_ROLE_MISMATCH'}
$commonStream=[IO.File]::Open($ActivationCommonPath,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);$memory=[IO.MemoryStream]::new();$commonStream.CopyTo($memory);$commonBytes=$memory.ToArray();$memory.Dispose();$commonStream.Position=0;$hash=[Security.Cryptography.SHA256]::Create();try{$actual=([BitConverter]::ToString($hash.ComputeHash($commonBytes)).Replace('-','').ToLowerInvariant())}finally{$hash.Dispose()};if($actual-cne$ActivationCommonSha256){$commonStream.Dispose();throw 'ACTIVATION_COMMON_IDENTITY_MISMATCH'};. ([ScriptBlock]::Create([Text.Encoding]::UTF8.GetString($commonBytes)))
# verify-activation is executed by the common v3 activation gate before mutation.
if($PSCmdlet.ShouldProcess($TaskName,'Verify signed G/P/A, enable, start, and require signed role readiness')){Invoke-PhaseBV3Activation $TaskName '\' $PrecommitRoot $AttestationPath $AttestationSignaturePath $PythonPath $V3CorePath $SshKeygenPath $PublicKeyPath $SignerIdentity $FirewallJson $ConfigAndKeyBindingsJson $ReadinessReceiptPath $ReadinessPublicKeyPath $ReadinessSignerIdentity $WindowsObserverPath $WindowsObserverSha256}

