[CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'High')]
param([Parameter(Mandatory=$true)][string]$BootstrapSha256,[Parameter(Mandatory=$true)][string]$SelfSha256,[Parameter(Mandatory=$true)][string]$PowerShellPath,[Parameter(Mandatory=$true)][string]$PowerShellSha256,[Parameter(Mandatory=$true)][string]$ReceiptPath,[Parameter(Mandatory=$true)][string]$ReceiptSha256,[Parameter(Mandatory=$true)][string]$InstallIdentity,[Parameter(Mandatory=$true)][string]$InstallRoot,[Parameter(Mandatory=$true)][string]$TaskActionSha256,[Parameter(Mandatory=$true)][string]$PhaseBSha256,[Parameter(Mandatory=$true)][string]$PhaseBCurrentPointer,[Parameter(Mandatory=$true)][string]$PhaseBCurrentPointerSha256,[switch]$Activate)
$ErrorActionPreference = 'Stop'
if($null-eq(Get-Command Assert-FinexExternalPretrustEntry -CommandType Function -ErrorAction SilentlyContinue)){throw'EXTERNAL_PRETRUST_LOADER_REQUIRED'};Assert-FinexExternalPretrustEntry $PSCommandPath 'activate'
function Open-PretrustHeldScript([string]$Path,[string]$Sha256,[string]$Reason){if(-not[IO.Path]::IsPathRooted($Path)){throw$Reason};$full=[IO.Path]::GetFullPath($Path);$resolved=(Resolve-Path -LiteralPath $Path).Path;if($full-cne$resolved){throw$Reason};$item=Get-Item -LiteralPath $resolved -Force;$chain=$item;while($null-ne$chain){if($chain.Attributes-band[IO.FileAttributes]::ReparsePoint){throw$Reason};$acl=Get-Acl -LiteralPath $chain.FullName;if(-not$acl.AreAccessRulesProtected){throw$Reason};$chain=if($chain-is[IO.DirectoryInfo]){$chain.Parent}else{$chain.Directory}};$stream=[IO.File]::Open($resolved,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);$memory=[IO.MemoryStream]::new();$stream.CopyTo($memory);$bytes=$memory.ToArray();$hash=[Security.Cryptography.SHA256]::Create();try{$actual=([BitConverter]::ToString($hash.ComputeHash($bytes)).Replace('-','').ToLowerInvariant())}finally{$hash.Dispose()};if($actual-cne$Sha256){$stream.Dispose();throw$Reason};$tokens=$null;$errors=$null;$text=[Text.UTF8Encoding]::new($false,$true).GetString($bytes);$ast=[Management.Automation.Language.Parser]::ParseInput($text,[ref]$tokens,[ref]$errors);if($errors.Count){$stream.Dispose();throw$Reason};$offset=if($null-ne$ast.ParamBlock){$ast.ParamBlock.Extent.EndOffset}else{0};$root=[IO.Path]::GetDirectoryName($resolved).Replace("'","''");$self=$resolved.Replace("'","''");$script=$text.Insert($offset,";`$PSScriptRoot='$root';`$PSCommandPath='$self';");return[pscustomobject]@{Bytes=$bytes;Created=$item.CreationTimeUtc;Length=$item.Length;Path=$resolved;Script=[ScriptBlock]::Create($script);Stream=$stream}}
function Close-PretrustHeldScript($Held,[string]$Reason){try{$item=Get-Item -LiteralPath $Held.Path -Force;if($item.CreationTimeUtc-ne$Held.Created-or$item.Length-ne$Held.Length){throw$Reason};$Held.Stream.Position=0;$memory=[IO.MemoryStream]::new();$Held.Stream.CopyTo($memory);$hash=[Security.Cryptography.SHA256]::Create();try{if(([BitConverter]::ToString($hash.ComputeHash($memory.ToArray())).Replace('-','').ToLowerInvariant())-cne([BitConverter]::ToString($hash.ComputeHash($Held.Bytes)).Replace('-','').ToLowerInvariant())){throw$Reason}}finally{$hash.Dispose()}}finally{$Held.Stream.Dispose()}}$bootstrap=Join-Path $PSScriptRoot 'OPERATOR_BOOTSTRAP.ps1';$heldBootstrap=Open-PretrustHeldScript $bootstrap $BootstrapSha256 'BOOTSTRAP_IDENTITY_MISMATCH';. $heldBootstrap.Script;Close-PretrustHeldScript $heldBootstrap 'BOOTSTRAP_POST_IDENTITY_MISMATCH';$phaseB=Join-Path $PSScriptRoot 'OPERATOR_PHASE_B.ps1';$heldPhaseB=Open-PretrustHeldScript $phaseB $PhaseBSha256 'PHASE_B_IDENTITY_MISMATCH';. $heldPhaseB.Script;Close-PretrustHeldScript $heldPhaseB 'PHASE_B_POST_IDENTITY_MISMATCH';$null=Assert-OperatorPinnedFile $PhaseBCurrentPointer $PhaseBCurrentPointerSha256 'PHASE_B_POINTER_IDENTITY_MISMATCH';Assert-OperatorPowerShellProcess $PowerShellPath $PowerShellSha256|Out-Null
$null=Assert-OperatorPinnedFile $PSCommandPath $SelfSha256 'SELF_IDENTITY_MISMATCH';$null=Assert-OperatorPinnedFile $PowerShellPath $PowerShellSha256 'POWERSHELL_IDENTITY_MISMATCH';$null=Assert-OperatorInstalledReceipt $ReceiptPath $ReceiptSha256 'finex-trusted-utc-fetcher-v1' $InstallIdentity $InstallRoot
if (-not $Activate) { throw 'EXPLICIT_ACTIVATE_SWITCH_REQUIRED' }
$taskName = 'AI_SCALPER_FINEX_TRUSTED_UTC_FETCHER_V1'
$task=Get-ScheduledTask -TaskName $taskName -ErrorAction Stop
$encodedMatch=[regex]::Match([string]$task.Actions[0].Arguments,'^-NoProfile -NonInteractive -EncodedCommand ([A-Za-z0-9+/=]+)$');if(-not$encodedMatch.Success){throw 'LEGACY_MUTABLE_RUNNER_ACTION_FORBIDDEN'};$loaderValues=Get-PhaseBEncodedLoaderValues $encodedMatch.Groups[1].Value;if($loaderValues[6]-cne[IO.Path]::GetFullPath($PhaseBCurrentPointer)){throw 'PHASE_B_POINTER_BINDING_MISMATCH'};if($loaderValues[22]-cne'active'){throw 'PHASE_B_ACTIVE_REQUIRED'};$runtimeSpec=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String([string]$loaderValues[20]))|ConvertFrom-Json;$pointerRaw=[Text.UTF8Encoding]::new($false,$true).GetString((Read-OperatorPinnedBytes $PhaseBCurrentPointer $PhaseBCurrentPointerSha256 'PHASE_B_POINTER_IDENTITY_MISMATCH'));if(-not$pointerRaw.EndsWith("`n")){throw 'PHASE_B_POINTER_NOT_CANONICAL'};$pointerEnvelope=$pointerRaw|ConvertFrom-Json;if((ConvertTo-OperatorCanonicalJson $pointerEnvelope)+"`n"-cne$pointerRaw-or$pointerEnvelope.schema_version-cne'finex-operator-receipt-current-envelope-v2'){throw 'PHASE_B_POINTER_NOT_CANONICAL'};$runtimeSpec.named.ReadinessGenerationId=[string]$pointerEnvelope.payload.generation_id;$runtimeSpec.named.ReadinessPointerSequence=[int]$pointerEnvelope.payload.sequence;$runtimeSpec.named.ReadinessPointerSha256=$PhaseBCurrentPointerSha256;if($task.State -ne 'Disabled' -or $task.Actions.Count-ne 1 -or $task.Triggers.Count -ne 0){throw 'TASK_NOT_DISABLED_OR_HAS_TRIGGER'}
$sha=[Security.Cryptography.SHA256]::Create();try{$text=[string]$task.Actions[0].Execute+[char]0+[string]$task.Actions[0].Arguments;$observed=([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($text))).Replace('-','').ToLowerInvariant())}finally{$sha.Dispose()}
if($observed -cne $TaskActionSha256){throw 'TASK_ACTION_IDENTITY_MISMATCH'}
if ($PSCmdlet.ShouldProcess($taskName, 'Enable and start dedicated trusted UTC fetcher')) {
    try{$challenge=New-OperatorReadinessChallenge $runtimeSpec $loaderValues ([string]$runtimeSpec.named.ReadinessGenerationId) $taskName;Enable-ScheduledTask -TaskName $taskName|Out-Null;Start-ScheduledTask -TaskName $taskName;Wait-OperatorSignedReadiness $taskName $loaderValues $runtimeSpec $challenge}catch{Stop-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue;Disable-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue|Out-Null;throw}
}
