[CmdletBinding()]
param(
 [Parameter(Mandatory=$true)][string]$BootstrapSha256,[Parameter(Mandatory=$true)][string]$SelfSha256,[Parameter(Mandatory=$true)][string]$RunnerSha256,
 [Parameter(Mandatory=$true)][string]$PowerShellPath,[Parameter(Mandatory=$true)][string]$PowerShellSha256,[Parameter(Mandatory=$true)][string]$PythonPath,[Parameter(Mandatory=$true)][string]$PythonSha256,
 [Parameter(Mandatory=$true)][string]$EntrypointPath,[Parameter(Mandatory=$true)][string]$EntrypointSha256,[Parameter(Mandatory=$true)][string]$ResponderCorePath,[Parameter(Mandatory=$true)][string]$ResponderCoreSha256,
 [Parameter(Mandatory=$true)][string]$AcceptanceCorePath,[Parameter(Mandatory=$true)][string]$AcceptanceCoreSha256,[Parameter(Mandatory=$true)][string]$ConfigPath,[Parameter(Mandatory=$true)][string]$ConfigSha256,
 [Parameter(Mandatory=$true)][string]$PhaseBSha256,[Parameter(Mandatory=$true)][string]$PhaseBEncodedCommand,[Parameter(Mandatory=$true)][string]$PhaseBEncodedCommandSha256,[Parameter(Mandatory=$true)][string]$PhaseBCurrentPointer,[Parameter(Mandatory=$true)][string]$PhaseBCurrentPointerSha256,[string]$InstalledReceiptSha256,[switch]$Install
)
$ErrorActionPreference='Stop';if($null-eq(Get-Command Assert-FinexExternalPretrustEntry -CommandType Function -ErrorAction SilentlyContinue)){throw'EXTERNAL_PRETRUST_LOADER_REQUIRED'};Assert-FinexExternalPretrustEntry $PSCommandPath 'install';$bootstrap=Join-Path $PSScriptRoot 'OPERATOR_BOOTSTRAP.ps1'
function Open-PretrustHeldScript([string]$Path,[string]$Sha256,[string]$Reason){if(-not[IO.Path]::IsPathRooted($Path)){throw$Reason};$full=[IO.Path]::GetFullPath($Path);$resolved=(Resolve-Path -LiteralPath $Path).Path;if($full-cne$resolved){throw$Reason};$item=Get-Item -LiteralPath $resolved -Force;$chain=$item;while($null-ne$chain){if($chain.Attributes-band[IO.FileAttributes]::ReparsePoint){throw$Reason};$acl=Get-Acl -LiteralPath $chain.FullName;if(-not$acl.AreAccessRulesProtected){throw$Reason};$chain=if($chain-is[IO.DirectoryInfo]){$chain.Parent}else{$chain.Directory}};$stream=[IO.File]::Open($resolved,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);$memory=[IO.MemoryStream]::new();$stream.CopyTo($memory);$bytes=$memory.ToArray();$hash=[Security.Cryptography.SHA256]::Create();try{$actual=([BitConverter]::ToString($hash.ComputeHash($bytes)).Replace('-','').ToLowerInvariant())}finally{$hash.Dispose()};if($actual-cne$Sha256){$stream.Dispose();throw$Reason};$tokens=$null;$errors=$null;$text=[Text.UTF8Encoding]::new($false,$true).GetString($bytes);$ast=[Management.Automation.Language.Parser]::ParseInput($text,[ref]$tokens,[ref]$errors);if($errors.Count){$stream.Dispose();throw$Reason};$offset=if($null-ne$ast.ParamBlock){$ast.ParamBlock.Extent.EndOffset}else{0};$root=[IO.Path]::GetDirectoryName($resolved).Replace("'","''");$self=$resolved.Replace("'","''");$script=$text.Insert($offset,";`$PSScriptRoot='$root';`$PSCommandPath='$self';");return[pscustomobject]@{Bytes=$bytes;Created=$item.CreationTimeUtc;Length=$item.Length;Path=$resolved;Script=[ScriptBlock]::Create($script);Stream=$stream}}
function Close-PretrustHeldScript($Held,[string]$Reason){try{$item=Get-Item -LiteralPath $Held.Path -Force;if($item.CreationTimeUtc-ne$Held.Created-or$item.Length-ne$Held.Length){throw$Reason};$Held.Stream.Position=0;$memory=[IO.MemoryStream]::new();$Held.Stream.CopyTo($memory);$hash=[Security.Cryptography.SHA256]::Create();try{if(([BitConverter]::ToString($hash.ComputeHash($memory.ToArray())).Replace('-','').ToLowerInvariant())-cne([BitConverter]::ToString($hash.ComputeHash($Held.Bytes)).Replace('-','').ToLowerInvariant())){throw$Reason}}finally{$hash.Dispose()}}finally{$Held.Stream.Dispose()}}$heldBootstrap=Open-PretrustHeldScript $bootstrap $BootstrapSha256 'BOOTSTRAP_IDENTITY_MISMATCH';. $heldBootstrap.Script;Close-PretrustHeldScript $heldBootstrap 'BOOTSTRAP_POST_IDENTITY_MISMATCH';$phaseB=Join-Path $PSScriptRoot 'OPERATOR_PHASE_B.ps1';$heldPhaseB=Open-PretrustHeldScript $phaseB $PhaseBSha256 'PHASE_B_IDENTITY_MISMATCH';. $heldPhaseB.Script;Close-PretrustHeldScript $heldPhaseB 'PHASE_B_POST_IDENTITY_MISMATCH';if((Get-OperatorTextSha256 $PhaseBEncodedCommand)-cne$PhaseBEncodedCommandSha256){throw 'PHASE_B_ENCODED_COMMAND_MISMATCH'};$loaderValues=Get-PhaseBEncodedLoaderValues $PhaseBEncodedCommand;if($loaderValues[6]-cne[IO.Path]::GetFullPath($PhaseBCurrentPointer)-or$loaderValues.Count-lt24-or$loaderValues[23]-cne$PhaseBCurrentPointerSha256){throw 'PHASE_B_POINTER_BINDING_MISMATCH'};if($loaderValues[22]-cne'active'){throw 'PHASE_B_ACTIVE_REQUIRED'};if(Test-Path -LiteralPath $PhaseBCurrentPointer){throw 'PHASE_B_POINTER_PREMATURE'};Assert-OperatorRestrictedAcl ([IO.Path]::GetDirectoryName([IO.Path]::GetFullPath($PhaseBCurrentPointer)));Assert-OperatorPowerShellProcess $PowerShellPath $PowerShellSha256|Out-Null
$sourceRunner=Join-Path $PSScriptRoot 'RUN_FINEX_TRUSTED_UTC_CAS_RESPONDER.ps1'
foreach($pin in @(@($PSCommandPath,$SelfSha256,'SELF_IDENTITY_MISMATCH'),@($sourceRunner,$RunnerSha256,'RUNNER_IDENTITY_MISMATCH'),@($PowerShellPath,$PowerShellSha256,'POWERSHELL_IDENTITY_MISMATCH'),@($PythonPath,$PythonSha256,'PYTHON_IDENTITY_MISMATCH'),@($EntrypointPath,$EntrypointSha256,'ENTRYPOINT_IDENTITY_MISMATCH'),@($ResponderCorePath,$ResponderCoreSha256,'RESPONDER_CORE_IDENTITY_MISMATCH'),@($AcceptanceCorePath,$AcceptanceCoreSha256,'ACCEPTANCE_CORE_IDENTITY_MISMATCH'),@($ConfigPath,$ConfigSha256,'CONFIG_IDENTITY_MISMATCH'))){$null=Assert-OperatorPinnedFile $pin[0] $pin[1] $pin[2]}
if(-not$Install){'PREFLIGHT_ONLY_USE_EXPLICIT_INSTALL_SWITCH';exit 0}
$taskName='AI_SCALPER_FINEX_TRUSTED_UTC_CAS_RESPONDER_V1';$root=Join-Path $env:ProgramData 'AI_SCALPER\FinexTrustedUtcCasResponderV1';$receipt=Join-Path $root 'install-receipt.json';$identity=Get-OperatorTextSha256 ([string]::Join('|',@($BootstrapSha256,$RunnerSha256,$PowerShellSha256,$PythonSha256,$EntrypointSha256,$ResponderCoreSha256,$AcceptanceCoreSha256,$ConfigSha256)))
if(Test-Path -LiteralPath $receipt -PathType Leaf){if([string]::IsNullOrEmpty($InstalledReceiptSha256)){throw 'INSTALLED_RECEIPT_PIN_REQUIRED'};$null=Assert-OperatorInstalledReceipt $receipt $InstalledReceiptSha256 'finex-trusted-utc-cas-responder-v1' $identity $root;'FINEX_TRUSTED_UTC_CAS_RESPONDER_INSTALL=ALREADY_INSTALLED_VALIDATED';exit 0}
if((Test-Path $root)-or(Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue)){throw 'INSTALL_RESOURCE_COLLISION'}
$created=$false;$taskCreated=$false
try{
 New-Item -ItemType Directory -Path (Join-Path $root 'live_runtime') -Force|Out-Null;$created=$true;$rootIdentity=(Get-Item -LiteralPath $root -Force).CreationTimeUtc.Ticks
 & icacls.exe $root /inheritance:r /grant:r "${env:USERDOMAIN}\${env:USERNAME}:(OI)(CI)F" 'Administrators:(OI)(CI)F' 'SYSTEM:(OI)(CI)F'|Out-Null;if($LASTEXITCODE-ne0){throw 'INSTALL_ACL_FAILED'}
 Copy-Item $EntrypointPath (Join-Path $root 'run_windows_trusted_utc_continuity_cas_responder.py');Copy-Item $ResponderCorePath (Join-Path $root 'live_runtime\windows_trusted_utc_continuity_cas_responder.py');Copy-Item $AcceptanceCorePath (Join-Path $root 'live_runtime\windows_trusted_utc_continuity_acceptance.py');Copy-Item $ConfigPath (Join-Path $root 'responder-config.json');Copy-Item $bootstrap $root;Copy-Item $phaseB $root;Copy-Item $sourceRunner $root
 $runner=Join-Path $root 'RUN_FINEX_TRUSTED_UTC_CAS_RESPONDER.ps1';$entry=Join-Path $root 'run_windows_trusted_utc_continuity_cas_responder.py';$config=Join-Path $root 'responder-config.json'
 $arguments="-NoProfile -NonInteractive -EncodedCommand $PhaseBEncodedCommand";$action=New-ScheduledTaskAction -Execute $PowerShellPath -Argument $arguments;$principal=New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType Interactive -RunLevel Highest;$settings=New-ScheduledTaskSettingsSet -ExecutionTimeLimit ([TimeSpan]::Zero) -RestartCount 3 -RestartInterval ([TimeSpan]::FromMinutes(1));$definition=New-ScheduledTask -Action $action -Principal $principal -Settings $settings;Register-ScheduledTask -TaskName $taskName -InputObject $definition|Out-Null;$taskCreated=$true;Disable-ScheduledTask -TaskName $taskName|Out-Null
 $manifest=@(@{path=$runner;sha256=$RunnerSha256},@{path=(Join-Path $root 'OPERATOR_BOOTSTRAP.ps1');sha256=$BootstrapSha256},@{path=$entry;sha256=$EntrypointSha256},@{path=(Join-Path $root 'live_runtime\windows_trusted_utc_continuity_cas_responder.py');sha256=$ResponderCoreSha256},@{path=(Join-Path $root 'live_runtime\windows_trusted_utc_continuity_acceptance.py');sha256=$AcceptanceCoreSha256},@{path=$config;sha256=$ConfigSha256});$metadata=[ordered]@{acceptance_core_sha256=$AcceptanceCoreSha256;bootstrap_sha256=$BootstrapSha256;config_sha256=$ConfigSha256;entrypoint_sha256=$EntrypointSha256;powershell_sha256=$PowerShellSha256;python_sha256=$PythonSha256;responder_core_sha256=$ResponderCoreSha256;runner_sha256=$RunnerSha256};$receiptSha=New-OperatorInstalledReceipt $receipt 'finex-trusted-utc-cas-responder-v1' $identity $manifest $taskName '' $metadata
}catch{if($taskCreated){Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue};if($created){Remove-OperatorCreatedRoot $root $rootIdentity};throw}
"FINEX_TRUSTED_UTC_CAS_RESPONDER_INSTALL=PASS_DISABLED:$identity`:RECEIPT:$receiptSha"
