[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$BootstrapSha256,
    [Parameter(Mandatory=$true)][string]$SelfSha256,
    [Parameter(Mandatory=$true)][string]$PowerShellPath,[Parameter(Mandatory=$true)][string]$PowerShellSha256,
    [Parameter(Mandatory=$true)][string]$BindingSha256,[Parameter(Mandatory=$true)][string]$SourceHostIdentitySha256,[Parameter(Mandatory=$true)][string]$ConsumerHostIdentitySha256,[Parameter(Mandatory=$true)][string]$AuthorityPublicKeySha256,
    [Parameter(Mandatory=$true)][string]$PublicKeyPath,[Parameter(Mandatory=$true)][string]$PublicKeyFileSha256,[Parameter(Mandatory=$true)][string]$ContinuityPath,[Parameter(Mandatory=$true)][string]$EnvelopePath,
    [Parameter(Mandatory=$true)][string]$PythonPath,[Parameter(Mandatory=$true)][string]$PythonSha256,[Parameter(Mandatory=$true)][string]$SshKeygenPath,[Parameter(Mandatory=$true)][string]$SshKeygenSha256,[Parameter(Mandatory=$true)][string]$CoreSha256,[Parameter(Mandatory=$true)][string]$RunnerSha256,[Parameter(Mandatory=$true)][string]$PhaseBSha256,[Parameter(Mandatory=$true)][string]$PhaseBEncodedCommand,[Parameter(Mandatory=$true)][string]$PhaseBEncodedCommandSha256,[Parameter(Mandatory=$true)][string]$PhaseBCurrentPointer,[Parameter(Mandatory=$true)][string]$PhaseBCurrentPointerSha256,[string]$InstalledReceiptSha256,[switch]$Install
)
function Open-PretrustHeldScript([string]$Path,[string]$Sha256,[string]$Reason){if(-not[IO.Path]::IsPathRooted($Path)){throw$Reason};$full=[IO.Path]::GetFullPath($Path);$resolved=(Resolve-Path -LiteralPath $Path).Path;if($full-cne$resolved){throw$Reason};$item=Get-Item -LiteralPath $resolved -Force;$chain=$item;while($null-ne$chain){if($chain.Attributes-band[IO.FileAttributes]::ReparsePoint){throw$Reason};$acl=Get-Acl -LiteralPath $chain.FullName;if(-not$acl.AreAccessRulesProtected){throw$Reason};$chain=if($chain-is[IO.DirectoryInfo]){$chain.Parent}else{$chain.Directory}};$stream=[IO.File]::Open($resolved,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);$memory=[IO.MemoryStream]::new();$stream.CopyTo($memory);$bytes=$memory.ToArray();$hash=[Security.Cryptography.SHA256]::Create();try{$actual=([BitConverter]::ToString($hash.ComputeHash($bytes)).Replace('-','').ToLowerInvariant())}finally{$hash.Dispose()};if($actual-cne$Sha256){$stream.Dispose();throw$Reason};$tokens=$null;$errors=$null;$text=[Text.UTF8Encoding]::new($false,$true).GetString($bytes);$ast=[Management.Automation.Language.Parser]::ParseInput($text,[ref]$tokens,[ref]$errors);if($errors.Count){$stream.Dispose();throw$Reason};$offset=if($null-ne$ast.ParamBlock){$ast.ParamBlock.Extent.EndOffset}else{0};$root=[IO.Path]::GetDirectoryName($resolved).Replace("'","''");$self=$resolved.Replace("'","''");$script=$text.Insert($offset,";`$PSScriptRoot='$root';`$PSCommandPath='$self';");return[pscustomobject]@{Bytes=$bytes;Created=$item.CreationTimeUtc;Length=$item.Length;Path=$resolved;Script=[ScriptBlock]::Create($script);Stream=$stream}}
function Close-PretrustHeldScript($Held,[string]$Reason){try{$item=Get-Item -LiteralPath $Held.Path -Force;if($item.CreationTimeUtc-ne$Held.Created-or$item.Length-ne$Held.Length){throw$Reason};$Held.Stream.Position=0;$memory=[IO.MemoryStream]::new();$Held.Stream.CopyTo($memory);$hash=[Security.Cryptography.SHA256]::Create();try{if(([BitConverter]::ToString($hash.ComputeHash($memory.ToArray())).Replace('-','').ToLowerInvariant())-cne([BitConverter]::ToString($hash.ComputeHash($Held.Bytes)).Replace('-','').ToLowerInvariant())){throw$Reason}}finally{$hash.Dispose()}}finally{$Held.Stream.Dispose()}}function Get-TextSha256([string]$Value){$sha=[Security.Cryptography.SHA256]::Create();try{return ([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Value))).Replace('-','').ToLowerInvariant())}finally{$sha.Dispose()}}
$ErrorActionPreference='Stop';if($null-eq(Get-Command Assert-FinexExternalPretrustEntry -CommandType Function -ErrorAction SilentlyContinue)){throw'EXTERNAL_PRETRUST_LOADER_REQUIRED'};Assert-FinexExternalPretrustEntry $PSCommandPath 'install';$bootstrap=Join-Path $PSScriptRoot 'OPERATOR_BOOTSTRAP.ps1';$heldBootstrap=Open-PretrustHeldScript $bootstrap $BootstrapSha256 'BOOTSTRAP_IDENTITY_MISMATCH';. $heldBootstrap.Script;Close-PretrustHeldScript $heldBootstrap 'BOOTSTRAP_POST_IDENTITY_MISMATCH';$phaseB=Join-Path $PSScriptRoot 'OPERATOR_PHASE_B.ps1';$heldPhaseB=Open-PretrustHeldScript $phaseB $PhaseBSha256 'PHASE_B_IDENTITY_MISMATCH';. $heldPhaseB.Script;Close-PretrustHeldScript $heldPhaseB 'PHASE_B_POST_IDENTITY_MISMATCH';if((Get-OperatorTextSha256 $PhaseBEncodedCommand)-cne$PhaseBEncodedCommandSha256){throw 'PHASE_B_ENCODED_COMMAND_MISMATCH'};$loaderValues=Get-PhaseBEncodedLoaderValues $PhaseBEncodedCommand;if($loaderValues[6]-cne[IO.Path]::GetFullPath($PhaseBCurrentPointer)-or$loaderValues.Count-lt24-or$loaderValues[23]-cne$PhaseBCurrentPointerSha256){throw 'PHASE_B_POINTER_BINDING_MISMATCH'};if($loaderValues[22]-cne'active'){throw 'PHASE_B_ACTIVE_REQUIRED'};$phaseCRuntimeArguments=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($loaderValues[20]))|ConvertFrom-Json;if($phaseCRuntimeArguments.named.Loop-ne$true){throw 'FETCHER_DURABLE_LOOP_REQUIRED'};if(Test-Path -LiteralPath $PhaseBCurrentPointer){throw 'PHASE_B_POINTER_PREMATURE'};Assert-OperatorRestrictedAcl ([IO.Path]::GetDirectoryName([IO.Path]::GetFullPath($PhaseBCurrentPointer)));Assert-OperatorPowerShellProcess $PowerShellPath $PowerShellSha256|Out-Null;$null=Assert-OperatorPinnedFile $PSCommandPath $SelfSha256 'SELF_IDENTITY_MISMATCH';$taskName='AI_SCALPER_FINEX_TRUSTED_UTC_FETCHER_V1';$installRoot=Join-Path $env:ProgramData 'AI_SCALPER\FinexTrustedUtcFetcherV1';$receipt=Join-Path $installRoot 'install-identity.sha256';$sourceCore=Join-Path $PSScriptRoot 'finex_trusted_utc.py';$sourceRunner=Join-Path $PSScriptRoot 'RUN_FINEX_TRUSTED_UTC_FETCHER.ps1'
function Assert-PinnedFile([string]$Path,[string]$Sha256,[string]$Reason){if(-not [IO.Path]::IsPathRooted($Path)){throw $Reason};$resolved=(Resolve-Path -LiteralPath $Path).Path;$item=Get-Item -LiteralPath $resolved -Force;if($item.PSIsContainer -or ($item.Attributes -band [IO.FileAttributes]::ReparsePoint)){throw $Reason};if((Get-FileHash -LiteralPath $resolved -Algorithm SHA256).Hash.ToLowerInvariant() -cne $Sha256){throw $Reason}}
function Assert-RestrictedAcl([string]$Path){$acl=Get-Acl -LiteralPath $Path;if(-not $acl.AreAccessRulesProtected){throw 'ACL_INHERITANCE_NOT_DISABLED'};$allowed=@("$env:USERDOMAIN\$env:USERNAME",'BUILTIN\Administrators','NT AUTHORITY\SYSTEM');foreach($rule in $acl.Access){if($rule.AccessControlType -eq 'Allow' -and $allowed -notcontains [string]$rule.IdentityReference){throw 'ACL_PRINCIPAL_INVALID'}}}
foreach($pin in @(@($PowerShellPath,$PowerShellSha256,'POWERSHELL_IDENTITY_MISMATCH'),@($PythonPath,$PythonSha256,'PYTHON_IDENTITY_MISMATCH'),@($SshKeygenPath,$SshKeygenSha256,'SSH_KEYGEN_IDENTITY_MISMATCH'),@($sourceCore,$CoreSha256,'CORE_IDENTITY_MISMATCH'),@($sourceRunner,$RunnerSha256,'RUNNER_IDENTITY_MISMATCH'),@($PublicKeyPath,$PublicKeyFileSha256,'PUBLIC_KEY_INVALID'))){Assert-PinnedFile $pin[0] $pin[1] $pin[2]}
$identitySha256=Get-TextSha256 ([string]::Join('|',@($SelfSha256,$BootstrapSha256,$PowerShellPath,$PowerShellSha256,$BindingSha256,$SourceHostIdentitySha256,$ConsumerHostIdentitySha256,$AuthorityPublicKeySha256,$PythonPath,$PythonSha256,$SshKeygenPath,$SshKeygenSha256,$CoreSha256,$RunnerSha256,$PublicKeyPath,$PublicKeyFileSha256,$ContinuityPath,$EnvelopePath)))
$preflightCursor=Join-Path ([IO.Path]::GetTempPath()) 'finex-trusted-utc-clean-host-cursor.json';$preflightEnvelope=Join-Path ([IO.Path]::GetTempPath()) 'finex-trusted-utc-clean-host-envelope.json'
& $sourceRunner -Preflight -BootstrapSha256 $BootstrapSha256 -PowerShellPath $PowerShellPath -PowerShellSha256 $PowerShellSha256 -PythonPath $PythonPath -PythonSha256 $PythonSha256 -SshKeygenPath $SshKeygenPath -SshKeygenSha256 $SshKeygenSha256 -CoreSha256 $CoreSha256 -RunnerSha256 $RunnerSha256 -PublicKeyPath $PublicKeyPath -PublicKeyFileSha256 $PublicKeyFileSha256 -ContinuityPath $preflightCursor -EnvelopePath $preflightEnvelope -BindingSha256 $BindingSha256 -SourceHostIdentitySha256 $SourceHostIdentitySha256 -ConsumerHostIdentitySha256 $ConsumerHostIdentitySha256 -AuthorityPublicKeySha256 $AuthorityPublicKeySha256
if(-not $Install){Write-Output 'PREFLIGHT_ONLY_USE_EXPLICIT_INSTALL_SWITCH';exit 0}
if(-not ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)){throw 'ADMINISTRATOR_REQUIRED'}
Assert-RestrictedAcl (Split-Path -Parent $ContinuityPath);Assert-RestrictedAcl (Split-Path -Parent $EnvelopePath)
if(Test-Path -LiteralPath $receipt -PathType Leaf){if([string]::IsNullOrEmpty($InstalledReceiptSha256)){throw 'INSTALLED_RECEIPT_PIN_REQUIRED'};$null=Assert-OperatorInstalledReceipt $receipt $InstalledReceiptSha256 'finex-trusted-utc-fetcher-v1' $identitySha256 $installRoot;Write-Output 'FINEX_TRUSTED_UTC_FETCHER_INSTALL=ALREADY_INSTALLED_VALIDATED';exit 0};if(Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue){throw 'INSTALL_RESOURCE_COLLISION'}
$createdRoot=$false;$createdTask=$false
try{New-Item -ItemType Directory -Path $installRoot -ErrorAction Stop|Out-Null;$createdRoot=$true;$rootIdentity=(Get-Item -LiteralPath $installRoot -Force).CreationTimeUtc.Ticks;& icacls.exe $installRoot /inheritance:r /grant:r "${env:USERDOMAIN}\${env:USERNAME}:(OI)(CI)F" 'Administrators:(OI)(CI)F' 'SYSTEM:(OI)(CI)F'|Out-Null;if($LASTEXITCODE -ne 0){throw 'INSTALL_ACL_FAILED'};Assert-RestrictedAcl $installRoot;Copy-Item -LiteralPath $sourceCore -Destination $installRoot;Copy-Item -LiteralPath $sourceRunner -Destination $installRoot;Copy-Item -LiteralPath $bootstrap -Destination $installRoot;Copy-Item -LiteralPath $phaseB -Destination $installRoot;$runner=Join-Path $installRoot 'RUN_FINEX_TRUSTED_UTC_FETCHER.ps1';$arguments="-NoProfile -NonInteractive -EncodedCommand $PhaseBEncodedCommand";$action=New-ScheduledTaskAction -Execute $PowerShellPath -Argument $arguments;$principal=New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType Interactive -RunLevel Highest;$settings=New-ScheduledTaskSettingsSet -ExecutionTimeLimit ([TimeSpan]::Zero);$definition=New-ScheduledTask -Action $action -Principal $principal -Settings $settings;Register-ScheduledTask -TaskName $taskName -InputObject $definition|Out-Null;$createdTask=$true;Disable-ScheduledTask -TaskName $taskName|Out-Null;$manifest=@(@{path=(Join-Path $installRoot 'finex_trusted_utc.py');sha256=$CoreSha256},@{path=$runner;sha256=$RunnerSha256},@{path=(Join-Path $installRoot 'OPERATOR_BOOTSTRAP.ps1');sha256=$BootstrapSha256});$metadata=[ordered]@{authority_public_key_sha256=$AuthorityPublicKeySha256;binding_sha256=$BindingSha256;bootstrap_sha256=$BootstrapSha256;consumer_host_identity_sha256=$ConsumerHostIdentitySha256;core_sha256=$CoreSha256;public_key_file_sha256=$PublicKeyFileSha256;python_sha256=$PythonSha256;runner_sha256=$RunnerSha256;source_host_identity_sha256=$SourceHostIdentitySha256;ssh_keygen_sha256=$SshKeygenSha256};$receiptSha256=New-OperatorInstalledReceipt $receipt 'finex-trusted-utc-fetcher-v1' $identitySha256 $manifest $taskName '' $metadata}catch{if($createdTask){Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue};if($createdRoot){Remove-OperatorCreatedRoot $installRoot $rootIdentity};throw}
$actionSha256=Get-TextSha256 ($PowerShellPath+[char]0+$arguments);Write-Output "FINEX_TRUSTED_UTC_FETCHER_INSTALL=PASS_DISABLED:$identitySha256`:ACTION:$actionSha256`:RECEIPT:$receiptSha256"
