[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param(
 [Parameter(Mandatory=$true)][string]$BootstrapSha256,[Parameter(Mandatory=$true)][string]$SelfSha256,
 [Parameter(Mandatory=$true)][string]$PowerShellPath,[Parameter(Mandatory=$true)][string]$PowerShellSha256,
 [Parameter(Mandatory=$true)][string]$PhaseBSha256,[Parameter(Mandatory=$true)][string]$PhaseBEncodedCommand,
 [Parameter(Mandatory=$true)][string]$CurrentPointer,[Parameter(Mandatory=$true)][string]$ExpectedPointerSha256,
 [Parameter(Mandatory=$true)][string]$PrecommitRoot,[Parameter(Mandatory=$true)][string]$PrecommitManifestSha256,[Parameter(Mandatory=$true)][ValidateSet('finex-cas','finex-fetcher','putra-producer')][string]$OperatorRole,
 [Parameter(Mandatory=$true)][string]$TaskName,[Parameter(Mandatory=$true)][string]$ReceiptSignerIdentity,
 [Parameter(Mandatory=$true)][string]$ReceiptPublicKeyPath,[Parameter(Mandatory=$true)][string]$ReceiptPublicKeyFileSha256,
 [Parameter(Mandatory=$true)][string]$ReceiptPublicFingerprint,[Parameter(Mandatory=$true)][string]$SshKeygenPath,
 [Parameter(Mandatory=$true)][string]$SshKeygenSha256,[switch]$Publish)
$ErrorActionPreference='Stop'
if($null-eq(Get-Command Assert-FinexExternalPretrustEntry -CommandType Function -ErrorAction SilentlyContinue)){throw'EXTERNAL_PRETRUST_LOADER_REQUIRED'}
Assert-FinexExternalPretrustEntry $PSCommandPath 'publish';if(-not$Publish){throw'EXPLICIT_PHASE_C_PUBLISH_REQUIRED'}
function H([byte[]]$b){$x=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($x.ComputeHash($b)).Replace('-','').ToLowerInvariant())}finally{$x.Dispose()}}
function O([string]$p,[string]$sha,[string]$why){if(-not[IO.Path]::IsPathRooted($p)){throw$why};$full=[IO.Path]::GetFullPath($p);$resolved=(Resolve-Path -LiteralPath $p).Path;if($full-cne$resolved){throw$why};$i=Get-Item -LiteralPath $resolved -Force;$chain=$i;while($null-ne$chain){if($chain.Attributes-band[IO.FileAttributes]::ReparsePoint){throw$why};$chain=if($chain.PSIsContainer){$chain.Parent}else{$chain.Directory}};$f=[IO.File]::Open($resolved,'Open','Read','Read');$m=[IO.MemoryStream]::new();$f.CopyTo($m);$b=$m.ToArray();if($sha-and(H $b)-cne$sha){$f.Dispose();throw$why};[pscustomobject]@{Bytes=$b;File=$f;Path=$resolved}}
function J($o,[string]$why){$raw=[Text.UTF8Encoding]::new($false,$true).GetString($o.Bytes);if(-not$raw.EndsWith("`n")){throw$why};$v=$raw|ConvertFrom-Json;if(($v|ConvertTo-Json -Depth 60 -Compress)+"`n"-cne$raw){throw$why};$v}
function K($o,[string[]]$keys,[string]$why){if((@($o.PSObject.Properties.Name|Sort-Object)-join[char]0)-cne(@($keys|Sort-Object)-join[char]0)){throw$why}}
function V([byte[]]$data,[byte[]]$sig,[string]$ns){$a=[IO.Path]::GetTempFileName();$s=[IO.Path]::GetTempFileName();try{[IO.File]::WriteAllText($a,$ReceiptSignerIdentity+' '+([Text.Encoding]::ASCII.GetString($public.Bytes).Trim())+"`n",[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllBytes($s,$sig);$q=[Diagnostics.ProcessStartInfo]::new($ssh.Path,"-Y verify -f `"$a`" -I `"$ReceiptSignerIdentity`" -n `"$ns`" -s `"$s`"");$q.UseShellExecute=$false;$q.RedirectStandardInput=$true;$q.RedirectStandardError=$true;$p=[Diagnostics.Process]::Start($q);$p.StandardInput.BaseStream.Write($data,0,$data.Length);$p.StandardInput.Close();$p.WaitForExit();if($p.ExitCode-ne0){throw'PRECOMMIT_SIGNATURE_INVALID'}}finally{Remove-Item $a,$s -Force -ErrorAction SilentlyContinue}}
$held=@();$lock=$null
try{
 $bootstrap=O (Join-Path $PSScriptRoot 'OPERATOR_BOOTSTRAP.ps1') $BootstrapSha256 'BOOTSTRAP_IDENTITY_MISMATCH';$held+=$bootstrap;$phaseB=O (Join-Path $PSScriptRoot 'OPERATOR_PHASE_B.ps1') $PhaseBSha256 'PHASE_B_IDENTITY_MISMATCH';$held+=$phaseB;$self=O $PSCommandPath $SelfSha256 'SELF_IDENTITY_MISMATCH';$held+=$self;$power=O $PowerShellPath $PowerShellSha256 'POWERSHELL_IDENTITY_MISMATCH';$held+=$power;$ssh=O $SshKeygenPath $SshKeygenSha256 'SSH_KEYGEN_IDENTITY_MISMATCH';$held+=$ssh;$public=O $ReceiptPublicKeyPath $ReceiptPublicKeyFileSha256 'RECEIPT_PUBLIC_KEY_INVALID';$held+=$public
 if((Get-Process -Id $PID).Path-cne$power.Path){throw'POWERSHELL_PROCESS_IDENTITY_MISMATCH'};. ([ScriptBlock]::Create([Text.UTF8Encoding]::new($false,$true).GetString($bootstrap.Bytes)));. ([ScriptBlock]::Create([Text.UTF8Encoding]::new($false,$true).GetString($phaseB.Bytes)));$parts=([Text.Encoding]::ASCII.GetString($public.Bytes).Trim()-split'\s+');if($parts.Count-lt2-or$parts[0]-cne'ssh-ed25519'-or(H ([Convert]::FromBase64String($parts[1])))-cne$ReceiptPublicFingerprint){throw'RECEIPT_PUBLIC_KEY_FINGERPRINT_MISMATCH'}
 $root=[IO.Path]::GetFullPath($PrecommitRoot);$manifest=O (Join-Path $root 'precommit.json') $PrecommitManifestSha256 'PRECOMMIT_MANIFEST_INVALID';$held+=$manifest;$plan=J $manifest 'PRECOMMIT_MANIFEST_INVALID';K $plan @('future_pointer_path','generation_id','generation_receipt_sha256','generation_signature_sha256','operator_role','pointer_sha256','predecessor_generation_id','receipt_namespace','receipt_public_fingerprint','receipt_signer_identity','schema_version','sequence','task_topology_sha256') 'PRECOMMIT_MANIFEST_INVALID'
 $requiredSigner=if($OperatorRole-eq'putra-producer'){'putra-phase-d-operator'}else{'finex-phase-d-operator'};if($ReceiptSignerIdentity-cne$requiredSigner-or$plan.schema_version-cne'finex-phase-b-precommit-plan-v1'-or$plan.operator_role-cne$OperatorRole-or$plan.future_pointer_path-cne[IO.Path]::GetFullPath($CurrentPointer)-or$plan.pointer_sha256-cne$ExpectedPointerSha256-or$plan.receipt_public_fingerprint-cne$ReceiptPublicFingerprint-or$plan.receipt_signer_identity-cne$ReceiptSignerIdentity-or$plan.receipt_namespace-cne'ai-scalper-finex-operator-install-receipt-v1'){throw'PRECOMMIT_BINDING_INVALID'}
 $pointer=O (Join-Path $root 'current.json') $ExpectedPointerSha256 'PRECOMMIT_POINTER_INVALID';$held+=$pointer;$pe=J $pointer 'PRECOMMIT_POINTER_INVALID';K $pe @('payload','schema_version','signature_base64') 'PRECOMMIT_POINTER_INVALID';$head=$pe.payload;K $head @('generation_id','predecessor_generation_id','receipt_sha256','schema_version','sequence','signature_sha256') 'PRECOMMIT_POINTER_INVALID';if($head.generation_id-cne$plan.generation_id-or$head.sequence-ne$plan.sequence-or$head.predecessor_generation_id-cne$plan.predecessor_generation_id-or$head.receipt_sha256-cne$plan.generation_receipt_sha256-or$head.signature_sha256-cne$plan.generation_signature_sha256){throw'PRECOMMIT_POINTER_INVALID'}
 V ([Text.UTF8Encoding]::new($false).GetBytes(($head|ConvertTo-Json -Depth 20 -Compress)+"`n")) ([Convert]::FromBase64String([string]$pe.signature_base64)) ($plan.receipt_namespace+'-pointer')
 $src=Join-Path (Join-Path $root 'current.json.generations') $plan.generation_id;$receipt=O (Join-Path $src 'receipt.json') $plan.generation_receipt_sha256 'PRECOMMIT_RECEIPT_INVALID';$held+=$receipt;$signature=O (Join-Path $src 'receipt.json.sig') $plan.generation_signature_sha256 'PRECOMMIT_RECEIPT_INVALID';$held+=$signature;V $receipt.Bytes $signature.Bytes $plan.receipt_namespace;$envelope=J $receipt 'PRECOMMIT_RECEIPT_INVALID';if($envelope.payload.task_topology.phase-cne'installed-disabled'-or$envelope.payload.task_topology.trigger_count-ne0-or$envelope.payload.task_topology.live_definition.state-cne'Disabled'-or(H ([Text.Encoding]::UTF8.GetBytes(($envelope.payload.task_topology|ConvertTo-Json -Depth 40 -Compress))))-cne$plan.task_topology_sha256){throw'PRECOMMIT_TOPOLOGY_INVALID'}
 $values=Get-PhaseBEncodedLoaderValues $PhaseBEncodedCommand;if($values[6]-cne[IO.Path]::GetFullPath($CurrentPointer)-or$values[22]-cne'active'-or$values[23]-cne$ExpectedPointerSha256){throw'PHASE_C_LOADER_BINDING_INVALID'};$task=Get-ScheduledTask -TaskName $TaskName -TaskPath '\' -ErrorAction Stop;if($task.State-ne'Disabled'-or@($task.Actions).Count-ne1-or@($task.Triggers).Count-ne0-or$task.Actions[0].Arguments-cne("-NoProfile -NonInteractive -EncodedCommand "+$PhaseBEncodedCommand)){throw'PHASE_C_TASK_NOT_DISABLED'};$live=Get-OperatorTaskRecord $TaskName;if(($live|ConvertTo-Json -Depth 40 -Compress)-cne($envelope.payload.task_topology.live_definition|ConvertTo-Json -Depth 40 -Compress)){throw'PHASE_C_LIVE_TOPOLOGY_DRIFT'}
 $current=[IO.Path]::GetFullPath($CurrentPointer);$generationRoot=$current+'.generations';if([IO.Path]::GetPathRoot($src)-cne[IO.Path]::GetPathRoot($generationRoot)){throw'PRECOMMIT_CROSS_VOLUME_FORBIDDEN'};if(-not$PSCmdlet.ShouldProcess($TaskName,'Adopt exact signed Phase B precommit')){return};$lockPath=$current+'.publish.lock';$lock=[IO.File]::Open($lockPath,'OpenOrCreate','ReadWrite','None')
 $replace=$false;$existingSha='';if(Test-Path $current){$existingHeld=O $current '' 'PHASE_C_EXISTING_POINTER_INVALID';try{$existingSha=H $existingHeld.Bytes;if($existingSha-ceq$ExpectedPointerSha256){'FINEX_PHASE_C_RECEIPT=ALREADY_PUBLISHED:'+$plan.generation_receipt_sha256;return};$existing=J $existingHeld 'PHASE_C_EXISTING_POINTER_INVALID';K $existing @('payload','schema_version','signature_base64') 'PHASE_C_EXISTING_POINTER_INVALID';K $existing.payload @('generation_id','predecessor_generation_id','receipt_sha256','schema_version','sequence','signature_sha256') 'PHASE_C_EXISTING_POINTER_INVALID';if($existing.schema_version-cne'finex-operator-receipt-current-envelope-v2'-or$existing.payload.schema_version-cne'finex-operator-receipt-current-payload-v2'){throw'PHASE_C_EXISTING_POINTER_INVALID'};V ([Text.UTF8Encoding]::new($false).GetBytes(($existing.payload|ConvertTo-Json -Depth 20 -Compress)+"`n")) ([Convert]::FromBase64String([string]$existing.signature_base64)) ($plan.receipt_namespace+'-pointer');if($plan.sequence-ne([long]$existing.payload.sequence+1)-or$plan.predecessor_generation_id-cne$existing.payload.generation_id){throw'PHASE_C_ANTI_ROLLBACK_CONFLICT'};$replace=$true}finally{$existingHeld.File.Dispose()}}elseif($plan.sequence-ne1-or$plan.predecessor_generation_id-cne('0'*32)){throw'PHASE_C_ANTI_ROLLBACK_CONFLICT'}
 $dest=Join-Path $generationRoot $plan.generation_id;[IO.Directory]::CreateDirectory($generationRoot)|Out-Null;if(Test-Path $dest){if((H ([IO.File]::ReadAllBytes((Join-Path $dest 'receipt.json'))))-cne$plan.generation_receipt_sha256-or(H ([IO.File]::ReadAllBytes((Join-Path $dest 'receipt.json.sig'))))-cne$plan.generation_signature_sha256){throw'PHASE_C_ORPHAN_CONFLICT'}}else{$stage=$dest+'.stage';[IO.Directory]::CreateDirectory($stage)|Out-Null;[IO.File]::WriteAllBytes((Join-Path $stage 'receipt.json'),$receipt.Bytes);[IO.File]::WriteAllBytes((Join-Path $stage 'receipt.json.sig'),$signature.Bytes);Move-Item -LiteralPath $stage -Destination $dest -ErrorAction Stop}
 if(-not(Test-Path $dest)){throw'PHASE_C_GENERATION_NOT_ADOPTED'};$tmp=$current+'.'+$plan.generation_id+'.tmp';[IO.File]::WriteAllBytes($tmp,$pointer.Bytes);if($replace){$recheck=O $current $existingSha 'PHASE_C_EXISTING_POINTER_DRIFT';$recheck.File.Dispose();$backup=$current+'.replaced-'+$plan.generation_id;$restore=$current+'.restore-'+$plan.generation_id;[IO.File]::WriteAllBytes($restore,$existingHeld.Bytes);try{[IO.File]::Replace($tmp,$current,$backup,$true);$replaced=O $backup $existingSha 'PHASE_C_REPLACED_PREDECESSOR_DRIFT';$replaced.File.Dispose()}catch{if(Test-Path $restore){[IO.File]::Replace($restore,$current,$null,$true)};throw}finally{Remove-Item $backup,$restore -Force -ErrorAction SilentlyContinue}}else{Move-Item -LiteralPath $tmp -Destination $current -ErrorAction Stop};'FINEX_PHASE_C_RECEIPT=PASS:'+$plan.generation_receipt_sha256
}finally{if($lock){$lock.Dispose()};foreach($item in $held){$item.File.Dispose()}}
