# EXTERNAL_PRETRUST_LOADER_REQUIRED: v3 uses held, hash-pinned inputs.
[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='High')]
param([Parameter(Mandatory=$true)][ValidateSet('finex-cas','finex-fetcher','putra-producer')][string]$OperatorRole,[Parameter(Mandatory=$true)][string]$TaskName,[string]$TaskPath='\',[Parameter(Mandatory=$true)][string]$PrecommitRoot,[Parameter(Mandatory=$true)][string]$AttestationPath,[Parameter(Mandatory=$true)][string]$AttestationSignaturePath,[Parameter(Mandatory=$true)][string]$CurrentPointer,[Parameter(Mandatory=$true)][string]$PythonPath,[Parameter(Mandatory=$true)][string]$V3CorePath,[Parameter(Mandatory=$true)][string]$SshKeygenPath,[Parameter(Mandatory=$true)][string]$PublicKeyPath,[Parameter(Mandatory=$true)][ValidateSet('finex-phase-d-operator','putra-phase-d-operator')][string]$SignerIdentity,[Parameter(Mandatory=$true)][string]$FirewallJson,[Parameter(Mandatory=$true)][string]$ConfigAndKeyBindingsJson,[Parameter(Mandatory=$true)][string]$PythonSha256,[Parameter(Mandatory=$true)][string]$V3CoreSha256,[Parameter(Mandatory=$true)][string]$SshKeygenSha256,[Parameter(Mandatory=$true)][string]$PublicKeySha256,[Parameter(Mandatory=$true)][string]$WindowsObserverPath,[Parameter(Mandatory=$true)][string]$WindowsObserverSha256,[switch]$Publish)
$ErrorActionPreference='Stop';if(-not$Publish){throw 'PHASE_B_V3_EXPLICIT_PUBLISH_REQUIRED'}
if(($OperatorRole-eq'putra-producer')-ne($SignerIdentity-eq'putra-phase-d-operator')){throw 'PHASE_B_V3_SIGNER_ROLE_MISMATCH'}
foreach($path in @($PrecommitRoot,$AttestationPath,$AttestationSignaturePath,$PythonPath,$V3CorePath,$SshKeygenPath,$PublicKeyPath,$FirewallJson,$ConfigAndKeyBindingsJson)){if(-not(Test-Path -LiteralPath $path)){throw 'PHASE_B_V3_PUBLISH_INPUT_MISSING'}}
function HOLD([string]$p,[string]$h,[string]$r){if(-not[IO.Path]::IsPathRooted($p)){throw$r};$full=[IO.Path]::GetFullPath($p);$resolved=(Resolve-Path -LiteralPath $p).Path;if($full-cne$resolved){throw$r};$chain=Get-Item -LiteralPath $resolved -Force;while($null-ne$chain){if($chain.Attributes-band[IO.FileAttributes]::ReparsePoint){throw$r};$chain=if($chain-is[IO.DirectoryInfo]){$chain.Parent}else{$chain.Directory}};$s=[IO.File]::Open($resolved,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);try{$m=[IO.MemoryStream]::new();$s.CopyTo($m);$b=$m.ToArray();$m.Dispose();$s.Position=0;$x=[Security.Cryptography.SHA256]::Create();try{$actual=([BitConverter]::ToString($x.ComputeHash($b)).Replace('-','').ToLowerInvariant())}finally{$x.Dispose()};if($actual-cne$h){throw $r};[pscustomobject]@{Stream=$s;Bytes=$b}}catch{$s.Dispose();throw}}
$holds=[Collections.Generic.List[object]]::new();try{$python=HOLD $PythonPath $PythonSha256 'PYTHON_IDENTITY_MISMATCH';$holds.Add($python);$core=HOLD $V3CorePath $V3CoreSha256 'V3_CORE_IDENTITY_MISMATCH';$holds.Add($core);$ssh=HOLD $SshKeygenPath $SshKeygenSha256 'SSH_KEYGEN_IDENTITY_MISMATCH';$holds.Add($ssh);$public=HOLD $PublicKeyPath $PublicKeySha256 'PUBLIC_KEY_IDENTITY_MISMATCH';$holds.Add($public);$observer=HOLD $WindowsObserverPath $WindowsObserverSha256 'WINDOWS_OBSERVER_IDENTITY_MISMATCH';$holds.Add($observer);. ([ScriptBlock]::Create([Text.Encoding]::UTF8.GetString($observer.Bytes)))
$firewall=Get-Content -Raw -LiteralPath $FirewallJson|ConvertFrom-Json;$bindings=Get-Content -Raw -LiteralPath $ConfigAndKeyBindingsJson|ConvertFrom-Json;$topology=Get-PhaseBV3WindowsTopology $TaskName $TaskPath $firewall $bindings
if($topology.state-cne'Disabled'-or$topology.trigger_count-ne0){throw 'PHASE_B_V3_PUBLISH_PRECONDITION_INVALID'}
$temporary=[IO.Path]::GetTempFileName();$recheck=[IO.Path]::GetTempFileName();try{Write-PhaseBV3CanonicalJson $topology $temporary;& $PythonPath $V3CorePath verify-publish --precommit $PrecommitRoot --live-topology $temporary --public-key $PublicKeyPath --signer-identity $SignerIdentity --ssh-keygen $SshKeygenPath --attestation $AttestationPath --attestation-signature $AttestationSignaturePath;if($LASTEXITCODE-ne0){throw 'PHASE_B_V3_PUBLISH_VERIFY_FAILED'};if(-not$PSCmdlet.ShouldProcess($TaskName,'Publish exact signed Phase B v3 pointer')){return};$topology2=Get-PhaseBV3WindowsTopology $TaskName $TaskPath $firewall $bindings;Write-PhaseBV3CanonicalJson $topology2 $recheck;if([Convert]::ToBase64String([IO.File]::ReadAllBytes($temporary))-cne[Convert]::ToBase64String([IO.File]::ReadAllBytes($recheck))){throw 'PHASE_B_V3_PUBLISH_TOPOLOGY_TOCTOU'};& $PythonPath $V3CorePath publish --precommit $PrecommitRoot --live-topology $recheck --public-key $PublicKeyPath --signer-identity $SignerIdentity --ssh-keygen $SshKeygenPath --attestation $AttestationPath --attestation-signature $AttestationSignaturePath --destination $CurrentPointer;if($LASTEXITCODE-ne0){throw 'PHASE_B_V3_PUBLISH_FAILED'}}finally{Remove-Item -LiteralPath $temporary,$recheck -Force -ErrorAction SilentlyContinue}
'PHASE_B_V3_PUBLISH=PASS:'+([IO.Path]::GetFullPath($CurrentPointer))}finally{foreach($held in $holds){$held.Stream.Dispose()}}
