[CmdletBinding()]
param(
 [Parameter(Mandatory=$true)][string]$BootstrapSha256,[Parameter(Mandatory=$true)][string]$SelfSha256,[Parameter(Mandatory=$true)][string]$PowerShellPath,[Parameter(Mandatory=$true)][string]$PowerShellSha256,[Parameter(Mandatory=$true)][string]$PythonPath,[Parameter(Mandatory=$true)][string]$PythonSha256,
 [Parameter(Mandatory=$true)][string]$EntrypointPath,[Parameter(Mandatory=$true)][string]$EntrypointSha256,
 [Parameter(Mandatory=$true)][string]$ResponderCoreSha256,[Parameter(Mandatory=$true)][string]$AcceptanceCoreSha256,
 [Parameter(Mandatory=$true)][string]$ConfigPath,[Parameter(Mandatory=$true)][string]$ConfigSha256,
 [Parameter(Mandatory=$true)][string]$OperatorCorePath,[Parameter(Mandatory=$true)][string]$OperatorCoreSha256,
 [Parameter(Mandatory=$true)][string]$RuntimeAclPolicyPath,[Parameter(Mandatory=$true)][string]$RuntimeAclPolicySha256,
 [Parameter(Mandatory=$true)][string]$SshKeygenPath,[Parameter(Mandatory=$true)][string]$SshKeygenSha256,
 [Parameter(Mandatory=$true)][string]$ReadinessChallengePath,[Parameter(Mandatory=$true)][string]$ReadinessReceiptPath,
 [Parameter(Mandatory=$true)][string]$ReadinessPrivateKeyPath,[Parameter(Mandatory=$true)][string]$ReadinessPublicKeyPath,
 [Parameter(Mandatory=$true)][string]$ReadinessPublicKeyFileSha256,[Parameter(Mandatory=$true)][string]$ReadinessPublicKeySha256,
 [Parameter(Mandatory=$true)][string]$ReadinessSignerIdentity,[Parameter(Mandatory=$true)][string]$ReadinessRole,
 [Parameter(Mandatory=$true)][string]$ReadinessTaskName,[Parameter(Mandatory=$true)][string]$ReadinessGenerationId,
 [Parameter(Mandatory=$true)][int]$ReadinessPointerSequence,[Parameter(Mandatory=$true)][string]$ReadinessPointerSha256,
 [Parameter(Mandatory=$true)][string]$SuccessEvidencePath,[switch]$Once
)
$ErrorActionPreference='Stop';if($null-eq(Get-Command Assert-OperatorPowerShellProcess -CommandType Function -ErrorAction SilentlyContinue)){throw 'HELD_BOOTSTRAP_CONTEXT_REQUIRED'};Assert-OperatorPowerShellProcess $PowerShellPath $PowerShellSha256|Out-Null
$null=Assert-OperatorPinnedFile $PSCommandPath $SelfSha256 'SELF_IDENTITY_MISMATCH';$null=Assert-OperatorPinnedFile $PowerShellPath $PowerShellSha256 'POWERSHELL_IDENTITY_MISMATCH';if((Get-Process -Id $PID).Path-cne(Resolve-Path -LiteralPath $PowerShellPath).Path){throw 'POWERSHELL_PROCESS_IDENTITY_MISMATCH'}
$null=Assert-OperatorPinnedFile (Join-Path $PSHOME 'powershell.exe') $PowerShellSha256 'POWERSHELL_IDENTITY_MISMATCH'
$entry=Assert-OperatorPinnedFile $EntrypointPath $EntrypointSha256 'ENTRYPOINT_IDENTITY_MISMATCH'
$runtime=Join-Path (Split-Path -Parent $entry) 'live_runtime';$null=Assert-OperatorPinnedFile (Join-Path $runtime 'windows_trusted_utc_continuity_cas_responder.py') $ResponderCoreSha256 'RESPONDER_CORE_IDENTITY_MISMATCH';$null=Assert-OperatorPinnedFile (Join-Path $runtime 'windows_trusted_utc_continuity_acceptance.py') $AcceptanceCoreSha256 'ACCEPTANCE_CORE_IDENTITY_MISMATCH';$null=Assert-OperatorPinnedFile $ConfigPath $ConfigSha256 'CONFIG_IDENTITY_MISMATCH'
$null=Assert-OperatorPinnedFile $OperatorCorePath $OperatorCoreSha256 'OPERATOR_CORE_IDENTITY_MISMATCH';$null=Assert-OperatorPinnedFile $SshKeygenPath $SshKeygenSha256 'SSH_KEYGEN_IDENTITY_MISMATCH';$null=Assert-OperatorPinnedFile $ReadinessPublicKeyPath $ReadinessPublicKeyFileSha256 'READINESS_PUBLIC_KEY_FILE_MISMATCH'
$releasePayload=[ordered]@{acceptance_core_sha256=$AcceptanceCoreSha256;entrypoint_sha256=$EntrypointSha256;python_sha256=$PythonSha256;responder_core_sha256=$ResponderCoreSha256};$releaseIdentity=Get-OperatorTextSha256 (ConvertTo-OperatorCanonicalJson $releasePayload)
$arguments=@($entry,'--config',$ConfigPath,'--config-sha256',$ConfigSha256,'--python-sha256',$PythonSha256,'--responder-core-sha256',$ResponderCoreSha256,'--acceptance-core-sha256',$AcceptanceCoreSha256,'--entrypoint-sha256',$EntrypointSha256,'--activation-challenge-path',$ReadinessChallengePath,'--readiness-role',$ReadinessRole,'--readiness-task-name',$ReadinessTaskName,'--readiness-generation-id',$ReadinessGenerationId,'--readiness-pointer-sequence',[string]$ReadinessPointerSequence,'--readiness-pointer-sha256',$ReadinessPointerSha256,'--readiness-public-key-sha256',$ReadinessPublicKeySha256)
if(-not('FinexCasKillJob'-as[type])){Add-Type -TypeDefinition @'
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;
public static class FinexCasKillJob {
 [StructLayout(LayoutKind.Sequential)] struct BASIC { public long PerProcessUserTimeLimit,PerJobUserTimeLimit; public uint LimitFlags; public UIntPtr MinimumWorkingSetSize,MaximumWorkingSetSize; public uint ActiveProcessLimit; public UIntPtr Affinity; public uint PriorityClass,SchedulingClass; }
 [StructLayout(LayoutKind.Sequential)] struct IO { public ulong ReadOperationCount,WriteOperationCount,OtherOperationCount,ReadTransferCount,WriteTransferCount,OtherTransferCount; }
 [StructLayout(LayoutKind.Sequential)] struct EXTENDED { public BASIC BasicLimitInformation; public IO IoInfo; public UIntPtr ProcessMemoryLimit,JobMemoryLimit,PeakProcessMemoryUsed,PeakJobMemoryUsed; }
 [DllImport("kernel32.dll",SetLastError=true)] static extern IntPtr CreateJobObject(IntPtr a,string n);
 [DllImport("kernel32.dll",SetLastError=true)] static extern bool SetInformationJobObject(IntPtr j,int c,IntPtr i,uint l);
 [DllImport("kernel32.dll",SetLastError=true)] static extern bool AssignProcessToJobObject(IntPtr j,IntPtr p);
 [DllImport("kernel32.dll",EntryPoint="CreateProcessW",ExactSpelling=true,SetLastError=true,CharSet=CharSet.Unicode)] static extern bool CreateProcessW(string app,System.Text.StringBuilder cmd,IntPtr pa,IntPtr ta,bool inherit,uint flags,IntPtr env,string cwd,ref STARTUPINFO si,out PROCESS_INFORMATION pi);
 [DllImport("kernel32.dll",SetLastError=true)] static extern uint ResumeThread(IntPtr h);
 [DllImport("kernel32.dll",SetLastError=true)] static extern bool TerminateProcess(IntPtr h,uint code);
 [DllImport("kernel32.dll",SetLastError=true)] static extern uint WaitForSingleObject(IntPtr h,uint ms);
 [DllImport("kernel32.dll",SetLastError=true)] public static extern bool CloseHandle(IntPtr h);
 [StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)] struct STARTUPINFO { public uint cb; public string reserved,desktop,title; public uint x,y,xSize,ySize,xChars,yChars,fill,flags; public ushort show,reserved2; public IntPtr reserved2Ptr,stdIn,stdOut,stdErr; }
 [StructLayout(LayoutKind.Sequential)] struct PROCESS_INFORMATION { public IntPtr process,thread; public uint processId,threadId; }
 public sealed class Owned { public Process Process; public IntPtr Job; public Owned(Process p,IntPtr j){Process=p;Job=j;} }
 public static Owned StartSuspended(string exe,string args){IntPtr j=CreateJobObject(IntPtr.Zero,null);if(j==IntPtr.Zero)throw new System.ComponentModel.Win32Exception();EXTENDED x=new EXTENDED();x.BasicLimitInformation.LimitFlags=0x2000;int n=Marshal.SizeOf(x);IntPtr q=Marshal.AllocHGlobal(n);PROCESS_INFORMATION pi=new PROCESS_INFORMATION();bool created=false;try{Marshal.StructureToPtr(x,q,false);if(!SetInformationJobObject(j,9,q,(uint)n))throw new System.ComponentModel.Win32Exception();STARTUPINFO si=new STARTUPINFO();si.cb=(uint)Marshal.SizeOf(si);var cmd=new System.Text.StringBuilder("\""+exe+"\" "+args);if(!CreateProcessW(exe,cmd,IntPtr.Zero,IntPtr.Zero,false,0x08000004,IntPtr.Zero,null,ref si,out pi))throw new System.ComponentModel.Win32Exception();created=true;if(!AssignProcessToJobObject(j,pi.process))throw new System.ComponentModel.Win32Exception();Process p=Process.GetProcessById((int)pi.processId);if(ResumeThread(pi.thread)==0xffffffff)throw new System.ComponentModel.Win32Exception();CloseHandle(pi.thread);pi.thread=IntPtr.Zero;CloseHandle(pi.process);pi.process=IntPtr.Zero;return new Owned(p,j);}catch{if(created&&pi.process!=IntPtr.Zero){TerminateProcess(pi.process,1);WaitForSingleObject(pi.process,5000);}if(pi.thread!=IntPtr.Zero)CloseHandle(pi.thread);if(pi.process!=IntPtr.Zero)CloseHandle(pi.process);CloseHandle(j);throw;}finally{Marshal.FreeHGlobal(q);}}
}
'@}
$challengeRaw=[Text.UTF8Encoding]::new($false,$true).GetString((Read-OperatorPinnedBytes $ReadinessChallengePath $env:AI_SCALPER_FINEX_READINESS_CHALLENGE_SHA256 'READINESS_CHALLENGE_CHANGED'));$challenge=$challengeRaw|ConvertFrom-Json;$staging=Join-Path ([IO.Path]::GetDirectoryName([IO.Path]::GetFullPath($SuccessEvidencePath))) ('.cas-evidence-'+[string]$challenge.nonce+'.staging');if(Test-Path -LiteralPath $staging){throw 'CAS_SUCCESS_EVIDENCE_STAGING_COLLISION'}
$probe=@($arguments)+@('--success-evidence-path',$staging,'--once');$probeQuoted=@($probe|ForEach-Object{'"'+([string]$_).Replace('"','\"')+'"'});$probeChild=$null;$probeJob=[IntPtr]::Zero
try{$probeOwned=[FinexCasKillJob]::StartSuspended($PythonPath,($probeQuoted-join' '));$probeChild=$probeOwned.Process;$probeJob=$probeOwned.Job;if(-not$probeChild.WaitForExit(45000)){$probeChild.Kill();$probeChild.WaitForExit();throw 'CAS_PROBE_TIMEOUT'};if($probeChild.ExitCode-ne0){throw ('CAS_PROBE_FAILED:'+ [string]$probeChild.ExitCode)};$stream=[IO.File]::Open($staging,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);try{$memory=[IO.MemoryStream]::new();$stream.CopyTo($memory);$evidenceBytes=$memory.ToArray()}finally{$stream.Dispose()};$encoded=[Convert]::ToBase64String($evidenceBytes)}finally{if($null-ne$probeChild-and-not$probeChild.HasExited){$probeChild.Kill();$probeChild.WaitForExit()};if($probeJob-ne[IntPtr]::Zero){[void][FinexCasKillJob]::CloseHandle($probeJob)}}
$adopt=@($OperatorCorePath,'--runtime-acl-policy-path',$RuntimeAclPolicyPath,'--runtime-acl-policy-sha256',$RuntimeAclPolicySha256,'adopt-success-evidence','--evidence-base64',$encoded,'--destination-path',$SuccessEvidencePath,'--challenge-path',$ReadinessChallengePath,'--role',$ReadinessRole,'--task-name',$ReadinessTaskName,'--generation-id',$ReadinessGenerationId,'--pointer-sequence',[string]$ReadinessPointerSequence,'--public-key-sha256',$ReadinessPublicKeySha256,'--expected-config-sha256',$ConfigSha256,'--expected-release-identity-sha256',$releaseIdentity);Invoke-OperatorPinnedPython $PythonPath $PythonSha256 $adopt;Remove-Item -LiteralPath $staging -Force
if($Once){return}
$durable=@($arguments)+@('--durable');$quoted=@($durable|ForEach-Object{'"'+([string]$_).Replace('"','\"')+'"'});$child=$null;$job=[IntPtr]::Zero
try{$owned=[FinexCasKillJob]::StartSuspended($PythonPath,($quoted-join' '));$child=$owned.Process;$job=$owned.Job;if($child.WaitForExit(1000)){throw 'CAS_DURABLE_EARLY_EXIT'};$readiness=@($OperatorCorePath,'--runtime-acl-policy-path',$RuntimeAclPolicyPath,'--runtime-acl-policy-sha256',$RuntimeAclPolicySha256,'emit-readiness','--challenge-path',$ReadinessChallengePath,'--receipt-path',$ReadinessReceiptPath,'--role',$ReadinessRole,'--task-name',$ReadinessTaskName,'--operation','verified_authoritative_cas_commit','--generation-id',$ReadinessGenerationId,'--pointer-sequence',[string]$ReadinessPointerSequence,'--ssh-keygen',$SshKeygenPath,'--private-key',$ReadinessPrivateKeyPath,'--public-key-sha256',$ReadinessPublicKeySha256,'--success-evidence-path',$SuccessEvidencePath,'--expected-config-sha256',$ConfigSha256,'--expected-release-identity-sha256',$releaseIdentity);Invoke-OperatorPinnedPython $PythonPath $PythonSha256 $readiness;$child.WaitForExit();throw ('CAS_DURABLE_EXITED:'+ [string]$child.ExitCode)}finally{if($null-ne$child-and-not$child.HasExited){$child.Kill();$child.WaitForExit()};if($job-ne[IntPtr]::Zero){[void][FinexCasKillJob]::CloseHandle($job)}}
