export const endpoints = {
  overview: '/overview',
  performance: '/performance',
  marketSymbols: '/market/symbols',
  marketQuote: (symbol: string) => `/market/${encodeURIComponent(symbol)}/quote`,
  marketCandles: (symbol: string) => `/market/${encodeURIComponent(symbol)}/candles`,
  marketIndicators: (symbol: string) => `/market/${encodeURIComponent(symbol)}/indicators`,
  marketStatus: (symbol: string) => `/market/${encodeURIComponent(symbol)}/status`,
  watchlist: '/watchlist',
  signals: '/signals',
  orders: '/orders',
  diagnostics: '/diagnostics',
  diagnosticsCalendar: '/diagnostics/calendar',
  diagnosticsCalendarSymbol: (symbol: string) => `/diagnostics/calendar/${encodeURIComponent(symbol)}`,
  risk: '/risk',
  quality: '/quality',
  health: '/health',
  systemStatus: '/system/status',
  systemAiAdvisory: '/system/ai-advisory',
  systemComponents: '/system/components',
  activity: '/activity',
  logs: '/logs',
  news: '/news',
  newsLatest: '/news/latest',
  newsBreaking: '/news/breaking',
  newsSentiment: '/news/sentiment/overview',
  newsSentimentTimeline: '/news/sentiment/timeline',
  newsProviders: '/news/providers',
  newsStatus: '/news/status',
  newsSymbolSummary: (symbol: string) => `/news/symbols/${encodeURIComponent(symbol)}/summary`,
  economicCalendar: '/economic-calendar',
  economicCalendarToday: '/economic-calendar/today',
  economicCalendarUpcoming: '/economic-calendar/upcoming',
  economicCalendarHighImpact: '/economic-calendar/high-impact',
  economicCalendarLive: '/economic-calendar/live',
  economicCalendarEvent: (eventId: string) => `/economic-calendar/${encodeURIComponent(eventId)}`,
  economicCalendarSymbol: (symbol: string) => `/economic-calendar/symbols/${encodeURIComponent(symbol)}`,
  economicCalendarCurrency: (currency: string) => `/economic-calendar/currencies/${encodeURIComponent(currency)}`,
  economicCalendarSources: '/economic-calendar/sources',
  economicCalendarHealth: '/economic-calendar/health',
  economicCalendarStatus: '/economic-calendar/status',
  economicCalendarGuard: (symbol: string) => `/economic-calendar/guard-preview/${encodeURIComponent(symbol)}`,
  economicCalendarMetrics: '/economic-calendar/metrics',
  economicCalendarAudit: (eventId: string) => `/economic-calendar/${encodeURIComponent(eventId)}/audit`,
} as const
