[CmdletBinding(DefaultParameterSetName='Status')]
param(
 [Parameter(ParameterSetName='Host',Mandatory=$true)][switch]$GenerateHostIdentity,[Parameter(ParameterSetName='Binding',Mandatory=$true)][switch]$GenerateBinding,[Parameter(ParameterSetName='Status')][switch]$Status,
 [Parameter(Mandatory=$true)][string]$PythonPath,[Parameter(Mandatory=$true)][string]$OutputPath,
 [Parameter(ParameterSetName='Host',Mandatory=$true)][ValidateSet('finex','putra')][string]$HostRole,[Parameter(ParameterSetName='Host',Mandatory=$true)][string]$TailscaleEvidenceJson,
 [Parameter(ParameterSetName='Host',Mandatory=$true)][ValidatePattern('^[0-9a-f]{64}$')][string]$ReleaseIdentitySha256,
 [Parameter(ParameterSetName='Host')][string]$ReceiptPrivateKeyPath,[Parameter(ParameterSetName='Host')][Parameter(ParameterSetName='Status')][string]$SshKeygenPath,[Parameter(ParameterSetName='Status')][string]$KeysPublicKeyPath,
 [Parameter(ParameterSetName='Binding',Mandatory=$true)][string]$FinexHostIdentityJson,[Parameter(ParameterSetName='Binding',Mandatory=$true)][string]$PutraHostIdentityJson,
 [Parameter(ParameterSetName='Binding',Mandatory=$true)][string]$FinexTailscaleIp,[Parameter(ParameterSetName='Binding',Mandatory=$true)][string]$PutraTailscaleIp,[Parameter(ParameterSetName='Binding')][ValidateRange(43130,43130)][int]$Port=43130,
 [Parameter(ParameterSetName='Binding',Mandatory=$true)][string]$CasProviderId,[Parameter(ParameterSetName='Binding',Mandatory=$true)][string]$AcceptanceCustodyIssuerId,[Parameter(ParameterSetName='Binding',Mandatory=$true)][string]$AcceptanceCustodyKeyId,
 [Parameter(ParameterSetName='Binding',Mandatory=$true)][ValidatePattern('^[0-9a-f]{64}$')][string]$BindingReleaseIdentitySha256,
 [Parameter(ParameterSetName='Status')][string]$KeysEvidence,[Parameter(ParameterSetName='Status')][string]$PublicHandoff,[Parameter(ParameterSetName='Status')][string]$HostIdentity,[Parameter(ParameterSetName='Status')][string]$JointBinding,[Parameter(ParameterSetName='Status')][string]$PhaseBPlan,[Parameter(ParameterSetName='Status')][string]$PreinstallEvidence
)
$ErrorActionPreference='Stop';$helper=Join-Path $PSScriptRoot 'phase_d_trust_contracts.py';if(-not(Test-Path $PythonPath -PathType Leaf)-or-not(Test-Path $helper -PathType Leaf)){throw 'PHASE_D_TRUST_TOOL_MISSING'}
if($PSCmdlet.ParameterSetName-eq'Host'){if((Test-Path $OutputPath)-or(Test-Path ($OutputPath+'.sig'))){throw 'HOST_IDENTITY_OUTPUT_COLLISION'};$machine=[string](Get-ItemPropertyValue -LiteralPath 'HKLM:\SOFTWARE\Microsoft\Cryptography' -Name MachineGuid);if([string]::IsNullOrWhiteSpace($machine)){throw 'MACHINE_IDENTITY_MISSING'};$sha=[Security.Cryptography.SHA256]::Create();try{$machineHash=([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes('ai-scalper-phase-d-machine-v1'+[char]0+$machine))).Replace('-','').ToLowerInvariant())}finally{$sha.Dispose()};& $PythonPath $helper host --role $HostRole --machine-identity-sha256 $machineHash --tailscale-evidence $TailscaleEvidenceJson --release-identity-sha256 $ReleaseIdentitySha256 --output $OutputPath;if($LASTEXITCODE-ne0){throw 'HOST_IDENTITY_GENERATION_FAILED'};$signRequested=(-not[string]::IsNullOrWhiteSpace($ReceiptPrivateKeyPath))-or(-not[string]::IsNullOrWhiteSpace($SshKeygenPath));if($signRequested){if([string]::IsNullOrWhiteSpace($ReceiptPrivateKeyPath)-or[string]::IsNullOrWhiteSpace($SshKeygenPath)){throw 'HOST_IDENTITY_SIGNING_CUSTODY_INCOMPLETE'};& $SshKeygenPath -Y sign -f $ReceiptPrivateKeyPath -n 'ai-scalper-phase-d-host-identity-v1' $OutputPath|Out-Null;if($LASTEXITCODE-ne0-or-not(Test-Path ($OutputPath+'.sig') -PathType Leaf)){throw 'HOST_IDENTITY_SIGN_FAILED'}};return}
if($PSCmdlet.ParameterSetName-eq'Binding'){if(Test-Path $OutputPath){throw 'JOINT_BINDING_OUTPUT_COLLISION'};& $PythonPath $helper binding --finex-identity $FinexHostIdentityJson --putra-identity $PutraHostIdentityJson --finex-ip $FinexTailscaleIp --putra-ip $PutraTailscaleIp --port $Port --cas-provider-id $CasProviderId --acceptance-custody-issuer-id $AcceptanceCustodyIssuerId --acceptance-custody-key-id $AcceptanceCustodyKeyId --release-identity-sha256 $BindingReleaseIdentitySha256 --output $OutputPath;if($LASTEXITCODE-ne0){throw 'JOINT_BINDING_GENERATION_FAILED'};return}
$arguments=@($helper,'status');foreach($pair in @(@('keys',$KeysEvidence),@('handoff',$PublicHandoff),@('identity',$HostIdentity),@('binding',$JointBinding),@('phase-b',$PhaseBPlan),@('preinstall',$PreinstallEvidence),@('ssh-keygen',$SshKeygenPath),@('keys-public-key',$KeysPublicKeyPath))){if(-not[string]::IsNullOrWhiteSpace([string]$pair[1])){$arguments+=@('--'+$pair[0],[string]$pair[1])}};$arguments+=@('--output',$OutputPath);& $PythonPath @arguments;if($LASTEXITCODE-ne0){throw 'PHASE_D_STATUS_FAILED'}
