[CmdletBinding(DefaultParameterSetName='Status')]
param(
 [Parameter(ParameterSetName='Status')][switch]$Status,
 [Parameter(ParameterSetName='Prepare',Mandatory=$true)][switch]$Prepare,
 [Parameter(ParameterSetName='KeysOnly',Mandatory=$true)][switch]$PrepareKeysOnly,
 [Parameter(ParameterSetName='KeysOnly',Mandatory=$true)][string]$KeyHandoffRoot,
 [Parameter(ParameterSetName='KeysOnly')][string]$SshRootOverride,
 [Parameter(ParameterSetName='Prepare',Mandatory=$true)][string]$RepoRoot,
 [Parameter(ParameterSetName='Prepare',Mandatory=$true)][string]$PreparationRoot,
 [Parameter(ParameterSetName='Prepare',Mandatory=$true)][string]$PowerShellPath,
 [Parameter(ParameterSetName='Prepare',Mandatory=$true)][string]$PythonPath,
 [Parameter(ParameterSetName='Prepare',Mandatory=$true)][Parameter(ParameterSetName='KeysOnly',Mandatory=$true)][string]$SshKeygenPath,
 [Parameter(ParameterSetName='Prepare',Mandatory=$true)][ValidatePattern('^[0-9a-f]{64}$')][string]$BindingSha256,
 [Parameter(ParameterSetName='Prepare',Mandatory=$true)][ValidatePattern('^[0-9a-f]{64}$')][string]$SourceHostIdentitySha256,
 [Parameter(ParameterSetName='Prepare',Mandatory=$true)][ValidatePattern('^[0-9a-f]{64}$')][string]$ConsumerHostIdentitySha256,
 [Parameter(ParameterSetName='Prepare',Mandatory=$true)][ValidatePattern('^[0-9a-f]{64}$')][string]$CustodyKeyFingerprintSha256,
 [Parameter(ParameterSetName='Prepare',Mandatory=$true)][string]$CasProviderId,
 [Parameter(ParameterSetName='Prepare',Mandatory=$true)][string]$CustodyIssuerId,
 [Parameter(ParameterSetName='Prepare',Mandatory=$true)][string]$CustodyKeyId,
 [Parameter(ParameterSetName='Prepare',Mandatory=$true)][string]$AcceptanceCustodyIssuerId,
 [Parameter(ParameterSetName='Prepare',Mandatory=$true)][string]$AcceptanceCustodyKeyId,
 [Parameter(ParameterSetName='Prepare',Mandatory=$true)][string]$HmacKeyPath,
 [Parameter(ParameterSetName='Prepare',Mandatory=$true)][string]$AuthorityPublicKeyPath,
 [Parameter(ParameterSetName='Prepare',Mandatory=$true)][string]$PhaseBInputsJson,
 [Parameter(ParameterSetName='Prepare')][string]$PostInstallInputsJson,
 [Parameter(ParameterSetName='Prepare')][string]$PhaseCInputsJson
)
$ErrorActionPreference='Stop'
function HashBytes([byte[]]$b){$h=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($h.ComputeHash($b)).Replace('-','').ToLowerInvariant())}finally{$h.Dispose()}}
function HashFile([string]$p){$s=[IO.File]::Open((Resolve-Path -LiteralPath $p).Path,'Open','Read','Read');try{$h=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($h.ComputeHash($s)).Replace('-','').ToLowerInvariant())}finally{$h.Dispose()}}finally{$s.Dispose()}}
function Canon([object]$v){if($null -eq $v){return 'null'};if($v -is [string]){return [string]($v|ConvertTo-Json -Compress)};if($v -is [bool]){if($v){return 'true'}else{return 'false'}};if($v -is [int] -or $v -is [long]){return [Convert]::ToString($v,[Globalization.CultureInfo]::InvariantCulture)};if($v -is [Collections.IDictionary]){$parts=@();foreach($entry in @($v.GetEnumerator()|Sort-Object Key)){$parts+=((Canon ([string]$entry.Key))+':'+(Canon ($entry.Value)))};return('{'+[string]::Join(',',$parts)+'}')};if($v -is [Collections.IEnumerable]){$parts=@();foreach($item in $v){$parts+=(Canon $item)};return('['+[string]::Join(',',$parts)+']')};$map=[ordered]@{};foreach($p in @($v.PSObject.Properties|Sort-Object Name)){$map[$p.Name]=$p.Value};return (Canon $map)}
function Relocate([object]$v,[string]$from,[string]$to){if($null -eq $v){return $null};if($v -is [string]){if($v -ceq $from){return $to};if($v.StartsWith($from+'\',[StringComparison]::OrdinalIgnoreCase)){return($to+$v.Substring($from.Length))};return $v};if($v -is [bool] -or $v -is [int] -or $v -is [long]){return $v};if($v -is [Collections.IDictionary]){$o=[ordered]@{};foreach($entry in $v.GetEnumerator()){$o[[string]$entry.Key]=(Relocate ($entry.Value) $from $to)};return $o};if($v -is [Collections.IEnumerable]){return ,@($v|ForEach-Object{Relocate $_ $from $to})};$o=[ordered]@{};foreach($p in $v.PSObject.Properties){$o[$p.Name]=(Relocate ($p.Value) $from $to)};$o}
function WriteCanon([string]$p,[object]$v){[IO.File]::WriteAllText($p,((Canon $v)+"`n"),[Text.UTF8Encoding]::new($false))}
function Protect([string]$p){$i=Get-Item -LiteralPath $p -Force;if($i.Attributes-band[IO.FileAttributes]::ReparsePoint){throw 'PREPARE_REPARSE_FORBIDDEN'};$identity=[Security.Principal.WindowsIdentity]::GetCurrent();$rights=if($i.PSIsContainer){'(OI)(CI)F'}else{'F'};$icacls=Join-Path $env:SystemRoot 'System32\icacls.exe';& $icacls $p /inheritance:r /remove:g '*S-1-1-0' /grant:r ($identity.Name+':'+$rights) '*S-1-5-18:F' '*S-1-5-32-544:F'|Out-Null;if($LASTEXITCODE-ne0){throw 'PREPARE_ACL_FAILED'};$acl=Get-Acl -LiteralPath $p;$allowed=@($identity.User.Value,'S-1-5-18','S-1-5-32-544');$invalid=@($acl.Access|Where-Object{($_.AccessControlType -ne 'Allow') -or ($_.IdentityReference.Translate([Security.Principal.SecurityIdentifier]).Value -notin $allowed)});if((-not $acl.AreAccessRulesProtected) -or ($invalid.Count -ne 0)){throw 'PREPARE_ACL_FAILED'}}function AssertSshRoot([string]$p){$i=Get-Item -LiteralPath $p -Force;if(-not$i.PSIsContainer-or($i.Attributes-band[IO.FileAttributes]::ReparsePoint)){throw 'PREPARE_SSH_DIRECTORY_ACL_INVALID'};$identity=[Security.Principal.WindowsIdentity]::GetCurrent();$allowed=@($identity.User.Value,'S-1-5-18','S-1-5-32-544');$acl=Get-Acl -LiteralPath $p;$invalid=@($acl.Access|Where-Object{($_.AccessControlType -ne 'Allow') -or ($_.IdentityReference.Translate([Security.Principal.SecurityIdentifier]).Value -notin $allowed)});if((-not $acl.AreAccessRulesProtected) -or ($invalid.Count -ne 0)){throw 'PREPARE_SSH_DIRECTORY_ACL_INVALID'}}function Fingerprint([string]$p){$q=([IO.File]::ReadAllText((Resolve-Path $p))).Trim()-split'\s+';if($q.Count-lt2-or$q[0]-cne'ssh-ed25519'){throw 'PREPARE_ED25519_PUBLIC_INVALID'};try{$b=[Convert]::FromBase64String($q[1])}catch{throw 'PREPARE_ED25519_PUBLIC_INVALID'};if($b.Length-ne51-or$b[0]-ne0-or$b[1]-ne0-or$b[2]-ne0-or$b[3]-ne11-or[Text.Encoding]::ASCII.GetString($b,4,11)-cne'ssh-ed25519'-or$b[15]-ne0-or$b[16]-ne0-or$b[17]-ne0-or$b[18]-ne32){throw 'PREPARE_ED25519_PUBLIC_INVALID'};HashBytes $b}
function InvokeEmptyPassphraseKeygen([string]$ssh,[string]$path,[string]$comment){if($ssh.Contains('"')-or$path.Contains('"')-or$comment.Contains('"')){throw 'PREPARE_KEY_ARGUMENT_INVALID'};$psi=[Diagnostics.ProcessStartInfo]::new();$psi.FileName=$ssh;$psi.Arguments='-q -t ed25519 -N "" -C "'+$comment+'" -f "'+$path+'"';$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$process=[Diagnostics.Process]::Start($psi);$stdout=$process.StandardOutput.ReadToEnd();$stderr=$process.StandardError.ReadToEnd();$process.WaitForExit();if($process.ExitCode-ne0){throw ('PREPARE_KEY_CREATE_FAILED:'+ $stderr.Trim())}}
function EnsureKey([string]$name,[string]$path,[string]$ssh){$private=Test-Path $path -PathType Leaf;$public=Test-Path ($path+'.pub') -PathType Leaf;if($private-xor$public){throw('PREPARE_KEYPAIR_PARTIAL:'+ $name)};if(-not$private){InvokeEmptyPassphraseKeygen $ssh $path ('ai-scalper-finex-'+$name+'-v1')};$derived=@(& $ssh -y -f $path);$expected=(([IO.File]::ReadAllText($path+'.pub')).Trim()-split'\s+')[0..1]-join' ';$derivedParts=if($derived.Count-eq1){@($derived[0].Trim()-split'\s+')}else{@()};$actual=if($derivedParts.Count-ge2){$derivedParts[0..1]-join' '}else{''};if($LASTEXITCODE-ne0-or$derived.Count-ne1-or$actual-cne$expected){throw('PREPARE_KEYPAIR_MISMATCH:'+ $name)};Protect $path;Protect ($path+'.pub');Fingerprint ($path+'.pub')}
function File([string]$p,[string]$reason){if(-not[IO.Path]::IsPathRooted($p)-or-not(Test-Path $p -PathType Leaf)){throw $reason};(Resolve-Path $p).Path}
$sshRoot=if($PSCmdlet.ParameterSetName-eq'KeysOnly'-and-not[string]::IsNullOrWhiteSpace($SshRootOverride)){if(-not[IO.Path]::IsPathRooted($SshRootOverride)){throw 'PREPARE_SSH_ROOT_OVERRIDE_NOT_ABSOLUTE'};[IO.Path]::GetFullPath($SshRootOverride)}else{Join-Path $HOME '.ssh'};$keys=[ordered]@{receipt=Join-Path $sshRoot 'ai_scalper_finex_receipt_ed25519';acceptance=Join-Path $sshRoot 'ai_scalper_finex_acceptance_ed25519';cas_readiness=Join-Path $sshRoot 'ai_scalper_finex_cas_readiness_ed25519';fetcher_readiness=Join-Path $sshRoot 'ai_scalper_finex_fetcher_readiness_ed25519'}
if($PSCmdlet.ParameterSetName-eq'Status'){$result=[ordered]@{};foreach($name in $keys.Keys){$result[$name]=[ordered]@{private_present=(Test-Path $keys[$name] -PathType Leaf);public_present=(Test-Path ($keys[$name]+'.pub') -PathType Leaf)}};Canon ([ordered]@{'keys'=$result;missing_external_values=@('BindingSha256','SourceHostIdentitySha256','ConsumerHostIdentitySha256','CustodyKeyFingerprintSha256','CasProviderId','CustodyIssuerId','CustodyKeyId','AcceptanceCustodyIssuerId','AcceptanceCustodyKeyId','HmacKeyPath','AuthorityPublicKeyPath','PhaseBInputsJson');private_keys_exported=$false;ready_to_prepare=$false;schema_version='finex-phase-d-preparation-status-v1'});return}
if($PSCmdlet.ParameterSetName-eq'KeysOnly'){$ssh=File $SshKeygenPath 'PREPARE_SSH_REQUIRED';$dest=[IO.Path]::GetFullPath($KeyHandoffRoot);if(Test-Path $dest){throw 'PREPARE_KEY_HANDOFF_COLLISION'};$parent=Split-Path $dest -Parent;[IO.Directory]::CreateDirectory($parent)|Out-Null;$stage=Join-Path $parent ('.finex-keys-'+[Guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($stage)|Out-Null;try{if(-not(Test-Path $sshRoot)){[IO.Directory]::CreateDirectory($sshRoot)|Out-Null;Protect $sshRoot}else{AssertSshRoot $sshRoot};$fps=[ordered]@{};foreach($name in $keys.Keys){$fps[$name]=EnsureKey $name $keys[$name] $ssh};if(@($fps.Values|Select-Object -Unique).Count-ne4){throw 'PREPARE_ROLE_KEY_REUSE_FORBIDDEN'};foreach($name in $keys.Keys){Copy-Item ($keys[$name]+'.pub') (Join-Path $stage ('finex_'+$name+'.pub'))};$evidence=Join-Path $stage 'key-custody-evidence.json';WriteCanon $evidence ([ordered]@{fingerprints=$fps;host_role='finex';private_keys_exported=$false;schema_version='finex-phase-d-key-custody-evidence-v1';signer_fingerprint_sha256=$fps.receipt});& $ssh -Y sign -f $keys.receipt -n 'ai-scalper-finex-phase-d-key-custody-v1' $evidence|Out-Null;if($LASTEXITCODE-ne0-or-not(Test-Path ($evidence+'.sig'))){throw 'PREPARE_KEY_EVIDENCE_SIGN_FAILED'};Get-ChildItem $stage -Force|%{Protect $_.FullName};Protect $stage;Move-Item $stage $dest;Canon ([ordered]@{handoff_root=$dest;private_keys_exported=$false;schema_version='finex-phase-d-key-handoff-result-v1'})}catch{if(Test-Path $stage){Remove-Item $stage -Recurse -Force -ErrorAction SilentlyContinue};throw};return}
$finalize=(-not[string]::IsNullOrWhiteSpace($PostInstallInputsJson))-and(-not[string]::IsNullOrWhiteSpace($PhaseCInputsJson));if((-not[string]::IsNullOrWhiteSpace($PostInstallInputsJson))-xor(-not[string]::IsNullOrWhiteSpace($PhaseCInputsJson))){throw 'PREPARE_FINALIZE_INPUT_PAIR_REQUIRED'}
$repo=(Resolve-Path $RepoRoot).Path;$dest=[IO.Path]::GetFullPath($PreparationRoot);if(Test-Path $dest){throw 'PREPARE_DESTINATION_COLLISION'};$parent=Split-Path $dest -Parent;[IO.Directory]::CreateDirectory($parent)|Out-Null;$stage=Join-Path $parent ('.finex-phase-d-'+[Guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($stage)|Out-Null
try{
 $power=File $PowerShellPath 'PREPARE_POWERSHELL_REQUIRED';$python=File $PythonPath 'PREPARE_PYTHON_REQUIRED';$ssh=File $SshKeygenPath 'PREPARE_SSH_REQUIRED';$hmac=File $HmacKeyPath 'PREPARE_HMAC_REQUIRED';$authority=File $AuthorityPublicKeyPath 'PREPARE_AUTHORITY_PUBLIC_REQUIRED';$phaseBPath=File $PhaseBInputsJson 'PREPARE_PHASE_B_REQUIRED';if($finalize){$postPath=File $PostInstallInputsJson 'PREPARE_POST_REQUIRED';$phaseCPath=File $PhaseCInputsJson 'PREPARE_PHASE_C_REQUIRED'}
 if(-not(Test-Path $sshRoot)){[IO.Directory]::CreateDirectory($sshRoot)|Out-Null;Protect $sshRoot}else{AssertSshRoot $sshRoot}
 $fps=[ordered]@{};foreach($name in $keys.Keys){$fps[$name]=EnsureKey $name $keys[$name] $ssh};if(@($fps.Values|Select-Object -Unique).Count-ne4){throw 'PREPARE_ROLE_KEY_REUSE_FORBIDDEN'}
 $validator=Join-Path $PSScriptRoot 'validate_phase_d_inputs.py';& $python $validator finex-phase-b $phaseBPath;if($LASTEXITCODE-ne0){throw 'PREPARE_PHASE_B_INVALID'};$phaseB=[IO.File]::ReadAllText($phaseBPath)|ConvertFrom-Json;if($finalize){& $python $validator finex-post-install $postPath;if($LASTEXITCODE-ne0){throw 'PREPARE_POST_INVALID'};& $python $validator finex-phase-c $phaseCPath;if($LASTEXITCODE-ne0){throw 'PREPARE_PHASE_C_INVALID'};$post=[IO.File]::ReadAllText($postPath)|ConvertFrom-Json;$phaseC=[IO.File]::ReadAllText($phaseCPath)|ConvertFrom-Json}
 foreach($d in @('arguments','configs','policies','public_handoff','release')){[IO.Directory]::CreateDirectory((Join-Path $stage $d))|Out-Null};foreach($name in $keys.Keys){Copy-Item ($keys[$name]+'.pub') (Join-Path $stage ('public_handoff\finex_'+$name+'.pub'))}
 $pack=Join-Path $repo 'operator_packs\finex_trusted_utc_v1';$bootstrap=Join-Path $pack 'OPERATOR_BOOTSTRAP.ps1';$phaseBScript=Join-Path $pack 'OPERATOR_PHASE_B.ps1';$core=Join-Path $pack 'finex_trusted_utc.py';$state=Join-Path $env:ProgramData 'AI_SCALPER\FinexTrustedUtcStateV1';$config=Join-Path $stage 'configs\cas-responder.json';WriteCanon $config ([ordered]@{acceptance_custody_issuer_id=$AcceptanceCustodyIssuerId;acceptance_custody_key_id=$AcceptanceCustodyKeyId;acceptance_private_key_path=$keys.acceptance;acceptance_public_key_file_sha256=HashFile ($keys.acceptance+'.pub');acceptance_public_key_path=($keys.acceptance+'.pub');acceptance_public_key_sha256=$fps.acceptance;clock_binding_sha256=$BindingSha256;consumer_host_identity_sha256=$ConsumerHostIdentitySha256;custody_issuer_id=$CustodyIssuerId;custody_key_fingerprint_sha256=$CustodyKeyFingerprintSha256;custody_key_id=$CustodyKeyId;database_path=Join-Path $state 'continuity-cas.sqlite3';hmac_key_path=$hmac;poll_interval_ms=250;provider_id=$CasProviderId;request_directory=Join-Path $state 'requests';response_directory=Join-Path $state 'responses';schema_version='windows-trusted-utc-continuity-cas-responder-v1';source_host_identity_sha256=$SourceHostIdentitySha256;ssh_keygen_path=$ssh;ssh_keygen_sha256=HashFile $ssh})
 $targets=Join-Path $stage 'policies\runtime_acl_policy_targets.json';WriteCanon $targets ([ordered]@{protected_paths=@($hmac,$keys.receipt,$keys.acceptance,$keys.cas_readiness,$keys.fetcher_readiness,$state,(Join-Path $dest 'configs\cas-responder.json'));schema_version='finex-phase-d-acl-targets-v1'});$policy=Join-Path $stage 'policies\runtime_acl_policy.json';$policyLocked=@($stage,(Join-Path $stage 'configs'),(Join-Path $stage 'policies'),$config);foreach($protectedTarget in $policyLocked){Protect $protectedTarget};& $python $core generate-acl-policy --output $policy --target $hmac --target $keys.receipt --target $keys.acceptance --target $keys.cas_readiness --target $keys.fetcher_readiness --target $state --target $config;if($LASTEXITCODE-ne0){throw 'PREPARE_POLICY_FAILED'};$policyValue=[IO.File]::ReadAllText($policy)|ConvertFrom-Json;WriteCanon $policy (Relocate $policyValue $stage $dest);if(([IO.File]::ReadAllText($policy)).Contains($stage)){throw 'PREPARE_POLICY_RELOCATION_FAILED'}
 $casInstall=Join-Path $pack 'INSTALL_FINEX_TRUSTED_UTC_CAS_RESPONDER.ps1';$fetchInstall=Join-Path $pack 'INSTALL_FINEX_TRUSTED_UTC_FETCHER.ps1';$casActivate=Join-Path $pack 'ACTIVATE_FINEX_TRUSTED_UTC_CAS_RESPONDER.ps1';$fetchActivate=Join-Path $pack 'ACTIVATE_FINEX_TRUSTED_UTC_FETCHER.ps1';$publisher=Join-Path $pack 'PUBLISH_FINEX_TRUSTED_UTC_PHASE_C.ps1';$publishedConfig=Join-Path $dest 'configs\cas-responder.json';$publishedPolicy=Join-Path $dest 'policies\runtime_acl_policy.json';$bootstrapHash=HashFile $bootstrap;$phaseBHash=HashFile $phaseBScript;$powerHash=HashFile $power
 $cas=[ordered]@{AcceptanceCorePath=Join-Path $repo 'live_runtime\windows_trusted_utc_continuity_acceptance.py';AcceptanceCoreSha256=HashFile (Join-Path $repo 'live_runtime\windows_trusted_utc_continuity_acceptance.py');BootstrapSha256=$bootstrapHash;ConfigPath=$publishedConfig;ConfigSha256=HashFile $config;EntrypointPath=Join-Path $repo 'run_windows_trusted_utc_continuity_cas_responder.py';EntrypointSha256=HashFile (Join-Path $repo 'run_windows_trusted_utc_continuity_cas_responder.py');Install=$true;PhaseBCurrentPointer=$phaseB.cas_pointer;PhaseBCurrentPointerSha256=$phaseB.cas_pointer_sha256;PhaseBEncodedCommand=$phaseB.cas_encoded;PhaseBEncodedCommandSha256=$phaseB.cas_encoded_sha256;PhaseBSha256=$phaseBHash;PowerShellPath=$power;PowerShellSha256=$powerHash;PythonPath=$python;PythonSha256=HashFile $python;ResponderCorePath=Join-Path $repo 'live_runtime\windows_trusted_utc_continuity_cas_responder.py';ResponderCoreSha256=HashFile (Join-Path $repo 'live_runtime\windows_trusted_utc_continuity_cas_responder.py');RunnerSha256=HashFile (Join-Path $pack 'RUN_FINEX_TRUSTED_UTC_CAS_RESPONDER.ps1');SelfSha256=HashFile $casInstall}
 $fetch=[ordered]@{AuthorityPublicKeySha256=Fingerprint $authority;BindingSha256=$BindingSha256;BootstrapSha256=$bootstrapHash;ConsumerHostIdentitySha256=$ConsumerHostIdentitySha256;ContinuityPath=Join-Path $state 'continuity.json';CoreSha256=HashFile $core;EnvelopePath=Join-Path $state 'envelope.json';Install=$true;PhaseBCurrentPointer=$phaseB.fetcher_pointer;PhaseBCurrentPointerSha256=$phaseB.fetcher_pointer_sha256;PhaseBEncodedCommand=$phaseB.fetcher_encoded;PhaseBEncodedCommandSha256=$phaseB.fetcher_encoded_sha256;PhaseBSha256=$phaseBHash;PowerShellPath=$power;PowerShellSha256=$powerHash;PublicKeyFileSha256=HashFile $authority;PublicKeyPath=$authority;PythonPath=$python;PythonSha256=HashFile $python;RunnerSha256=HashFile (Join-Path $pack 'RUN_FINEX_TRUSTED_UTC_FETCHER.ps1');SelfSha256=HashFile $fetchInstall;SourceHostIdentitySha256=$SourceHostIdentitySha256;SshKeygenPath=$ssh;SshKeygenSha256=HashFile $ssh};if($finalize){$cas.InstalledReceiptSha256=$post.cas_installed_receipt_sha256;$fetch.InstalledReceiptSha256=$post.fetcher_installed_receipt_sha256}
 $casPath=Join-Path $stage 'arguments\install-cas.json';$fetchPath=Join-Path $stage 'arguments\install-fetcher.json';WriteCanon $casPath $cas;WriteCanon $fetchPath $fetch;$build=@('-RepoRoot',$repo,'-OutputRoot',(Join-Path $stage 'release'),'-PowerShellPath',$power,'-PythonPath',$python,'-SshKeygenPath',$ssh,'-RuntimeAclPolicyPath',$policy,'-RuntimeAclPolicyPublishedPath',$publishedPolicy,'-ReceiptPublicKeyPath',($keys.receipt+'.pub'),'-AcceptancePublicKeyPath',($keys.acceptance+'.pub'),'-CasReadinessPublicKeyPath',($keys.cas_readiness+'.pub'),'-FetcherReadinessPublicKeyPath',($keys.fetcher_readiness+'.pub'),'-InstallCasArgumentsJson',$casPath,'-InstallFetcherArgumentsJson',$fetchPath)
 if($finalize){$ac=[ordered]@{Activate=$true;BootstrapSha256=$bootstrapHash;InstallIdentity=$post.cas_install_identity;InstallRoot=$post.cas_install_root;PhaseBCurrentPointer=$phaseB.cas_pointer;PhaseBCurrentPointerSha256=$phaseB.cas_pointer_sha256;PhaseBSha256=$phaseBHash;PowerShellPath=$power;PowerShellSha256=$powerHash;ReceiptPath=$post.cas_receipt_path;ReceiptSha256=$post.cas_receipt_sha256;SelfSha256=HashFile $casActivate;TaskActionSha256=$post.cas_task_action_sha256};$af=[ordered]@{Activate=$true;BootstrapSha256=$bootstrapHash;InstallIdentity=$post.fetcher_install_identity;InstallRoot=$post.fetcher_install_root;PhaseBCurrentPointer=$phaseB.fetcher_pointer;PhaseBCurrentPointerSha256=$phaseB.fetcher_pointer_sha256;PhaseBSha256=$phaseBHash;PowerShellPath=$power;PowerShellSha256=$powerHash;ReceiptPath=$post.fetcher_receipt_path;ReceiptSha256=$post.fetcher_receipt_sha256;SelfSha256=HashFile $fetchActivate;TaskActionSha256=$post.fetcher_task_action_sha256};$pc=[ordered]@{BootstrapSha256=$bootstrapHash;ConfigKeyJsonPath=$phaseC.config_key_path;ConfigKeyJsonSha256=$phaseC.config_key_sha256;CurrentPointer=$phaseB.cas_pointer;DependencyJsonPath=$phaseC.dependency_path;DependencyJsonSha256=$phaseC.dependency_sha256;FirewallJsonPath=$phaseC.firewall_path;FirewallJsonSha256=$phaseC.firewall_sha256;ImmutableJsonPath=$phaseC.immutable_path;ImmutableJsonSha256=$phaseC.immutable_sha256;MutableJsonPath=$phaseC.mutable_path;MutableJsonSha256=$phaseC.mutable_sha256;PhaseBEncodedCommand=$phaseB.cas_encoded;PhaseBSha256=$phaseBHash;PowerShellPath=$power;PowerShellSha256=$powerHash;Publish=$true;ReceiptPrivateKeyPath=$keys.receipt;ReceiptPublicFingerprint=$fps.receipt;ReceiptSignerIdentity='ai-scalper-finex-install-receipt-v1';RuntimeAclPolicyPath=$publishedPolicy;RuntimeAclPolicySha256=HashFile $policy;SelfSha256=HashFile $publisher;SshKeygenPath=$ssh;SshKeygenSha256=HashFile $ssh;TaskName='AI_SCALPER_FINEX_TRUSTED_UTC_CAS_RESPONDER_V1'};$acp=Join-Path $stage 'arguments\activate-cas.json';$afp=Join-Path $stage 'arguments\activate-fetcher.json';$pcp=Join-Path $stage 'arguments\publish-cas.json';WriteCanon $acp $ac;WriteCanon $afp $af;WriteCanon $pcp $pc;$build+=@('-ActivateCasArgumentsJson',$acp,'-ActivateFetcherArgumentsJson',$afp,'-PublishCasArgumentsJson',$pcp)}
 & (Join-Path $PSScriptRoot 'BUILD_FINEX_PHASE_D.ps1') @build -Build;if($LASTEXITCODE-ne0){throw 'PREPARE_BUILD_FAILED'};WriteCanon (Join-Path $stage 'preparation-result.json') ([ordered]@{fingerprints=$fps;phase=if($finalize){'FINALIZED'}else{'PREINSTALL'};private_keys_exported=$false;schema_version='finex-phase-d-preparation-result-v1'});Get-ChildItem $stage -Recurse -Force|Sort-Object FullName -Descending|%{if($_.FullName -notin $policyLocked){Protect $_.FullName}};Move-Item $stage $dest;Canon ([ordered]@{phase=if($finalize){'FINALIZED'}else{'PREINSTALL'};preparation_root=$dest;private_keys_exported=$false;schema_version='finex-phase-d-prepare-output-v1'})
}catch{if(Test-Path $stage){Remove-Item $stage -Recurse -Force -ErrorAction SilentlyContinue};throw}
