[CmdletBinding()]
param(
 [Parameter(Mandatory=$true)][string]$CasContractPath,[Parameter(Mandatory=$true)][string]$CasContractSha256,[Parameter(Mandatory=$true)][string]$FetcherContractPath,[Parameter(Mandatory=$true)][string]$FetcherContractSha256,
 [Parameter(Mandatory=$true)][string]$TrustedPythonPath,[Parameter(Mandatory=$true)][string]$TrustedPythonSha256,
 [Parameter(Mandatory=$true)][string]$TrustedV3CorePath,[Parameter(Mandatory=$true)][string]$TrustedV3CoreSha256,
 [Parameter(Mandatory=$true)][string]$TrustedSshKeygenPath,[Parameter(Mandatory=$true)][string]$TrustedSshKeygenSha256,
 [Parameter(Mandatory=$true)][string]$TrustedPublicKeyPath,[Parameter(Mandatory=$true)][string]$TrustedPublicKeySha256,
 [Parameter(Mandatory=$true)][string]$TrustedObserverPath,[Parameter(Mandatory=$true)][string]$TrustedObserverSha256,
 [Parameter(Mandatory=$true)][ValidateSet('finex-phase-d-operator')][string]$TrustedSignerIdentity
)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
if($null-eq(Get-Command Assert-FinexExternalPretrustEntry -CommandType Function -ErrorAction SilentlyContinue)){throw 'EXTERNAL_PRETRUST_LOADER_REQUIRED'}
Assert-FinexExternalPretrustEntry $PSCommandPath 'status'
$schemas=@('finex-phase-b-precommit-plan-v3','finex-phase-b-pointer-envelope-v3','finex-phase-b-materialized-loader-v3','finex-phase-b-topology-attestation-v3','finex-role-readiness-challenge-v3','finex-role-readiness-envelope-v1')
$exact=@('attestation_path','attestation_signature_path','config_and_key_bindings_json','consumer_host_identity_sha256','expected_host_role','firewall_json','host_identity_sha256','joint_binding_sha256','operator_role','precommit_root','public_key','public_key_sha256','python_path','python_sha256','readiness_identity','readiness_path','readiness_public_key','release_identity_sha256','schema_version','source_host_identity_sha256','signer_identity','ssh_keygen_path','ssh_keygen_sha256','task_name','task_path','v3_core_path','v3_core_sha256','windows_observer_path','windows_observer_sha256')
function HOLD([string]$Path,[string]$Sha256,[string]$Reason){if(-not[IO.Path]::IsPathRooted($Path)){throw $Reason};$full=[IO.Path]::GetFullPath($Path);$resolved=(Resolve-Path -LiteralPath $Path).Path;if($full-cne$resolved){throw $Reason};$chain=Get-Item -LiteralPath $resolved -Force;while($null-ne$chain){if($chain.Attributes-band[IO.FileAttributes]::ReparsePoint){throw $Reason};$chain=if($chain-is[IO.DirectoryInfo]){$chain.Parent}else{$chain.Directory}};$s=[IO.File]::Open($resolved,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);try{$m=[IO.MemoryStream]::new();$s.CopyTo($m);$b=$m.ToArray();$m.Dispose();$s.Position=0;$h=[Security.Cryptography.SHA256]::Create();try{$actual=([BitConverter]::ToString($h.ComputeHash($b)).Replace('-','').ToLowerInvariant())}finally{$h.Dispose()};if($actual-cne$Sha256){throw $Reason};[pscustomobject]@{Stream=$s;Bytes=$b;Path=$resolved}}catch{$s.Dispose();throw}}
function PY($Python,$Core,[string[]]$Arguments){$encoded=[Convert]::ToBase64String($Core.Bytes);$runner="import base64,sys;src=base64.b64decode('$encoded');sys.argv=[sys.argv[1]]+sys.argv[2:];g={'__name__':'__main__','__file__':sys.argv[0]};exec(compile(src,sys.argv[0],'exec'),g,g)";& $Python.Path -I -B -c $runner @Arguments;if($LASTEXITCODE-ne0){throw 'PHASE_D_V3_HELD_VERIFIER_FAILED'}}
$results=@();$expectedRoles=@('finex-cas','finex-fetcher');$expectedTasks=@('AI_SCALPER_FINEX_TRUSTED_UTC_CAS_RESPONDER_V1','AI_SCALPER_FINEX_TRUSTED_UTC_FETCHER_V1');$seenTasks=@{}
for($contractIndex=0;$contractIndex-lt2;$contractIndex++){
 $contractPath=@($CasContractPath,$FetcherContractPath)[$contractIndex];$contractSha=@($CasContractSha256,$FetcherContractSha256)[$contractIndex];$contract=HOLD $contractPath $contractSha 'PHASE_D_V3_STATUS_CONTRACT_IDENTITY_MISMATCH';try{$c=[Text.Encoding]::UTF8.GetString($contract.Bytes)|ConvertFrom-Json}finally{$contract.Stream.Dispose()};$actual=@($c.PSObject.Properties.Name|Sort-Object)
 if($c.schema_version-cne'finex-phase-d-role-status-v3'-or(Compare-Object $exact $actual)-or$c.expected_host_role-cne'finex'-or@($c.consumer_host_identity_sha256,$c.host_identity_sha256,$c.joint_binding_sha256,$c.release_identity_sha256,$c.source_host_identity_sha256|Where-Object{$_-notmatch'^[0-9a-f]{64}$'}).Count-or$c.operator_role-cne$expectedRoles[$contractIndex]-or$c.task_name-cne$expectedTasks[$contractIndex]-or$seenTasks.ContainsKey([string]$c.task_name)){throw 'PHASE_D_V3_STATUS_CONTRACT_INVALID'};$seenTasks[[string]$c.task_name]=$true
 if([IO.Path]::GetFullPath([string]$c.python_path)-cne[IO.Path]::GetFullPath($TrustedPythonPath)-or$c.python_sha256-cne$TrustedPythonSha256-or[IO.Path]::GetFullPath([string]$c.v3_core_path)-cne[IO.Path]::GetFullPath($TrustedV3CorePath)-or$c.v3_core_sha256-cne$TrustedV3CoreSha256-or[IO.Path]::GetFullPath([string]$c.ssh_keygen_path)-cne[IO.Path]::GetFullPath($TrustedSshKeygenPath)-or$c.ssh_keygen_sha256-cne$TrustedSshKeygenSha256-or[IO.Path]::GetFullPath([string]$c.public_key)-cne[IO.Path]::GetFullPath($TrustedPublicKeyPath)-or$c.public_key_sha256-cne$TrustedPublicKeySha256-or[IO.Path]::GetFullPath([string]$c.windows_observer_path)-cne[IO.Path]::GetFullPath($TrustedObserverPath)-or$c.windows_observer_sha256-cne$TrustedObserverSha256-or$c.signer_identity-cne$TrustedSignerIdentity){throw 'PHASE_D_V3_PRETRUST_ARGUMENT_MISMATCH'}
 $holds=[Collections.Generic.List[object]]::new();$materializedTemp=[IO.Path]::GetTempFileName();$temp=$null
 try{
  $python=HOLD $TrustedPythonPath $TrustedPythonSha256 'PHASE_D_V3_PYTHON_IDENTITY_MISMATCH';$holds.Add($python);$core=HOLD $TrustedV3CorePath $TrustedV3CoreSha256 'PHASE_D_V3_CORE_IDENTITY_MISMATCH';$holds.Add($core);$ssh=HOLD $TrustedSshKeygenPath $TrustedSshKeygenSha256 'PHASE_D_V3_SSH_IDENTITY_MISMATCH';$holds.Add($ssh);$public=HOLD $TrustedPublicKeyPath $TrustedPublicKeySha256 'PHASE_D_V3_PUBLIC_KEY_IDENTITY_MISMATCH';$holds.Add($public)
  PY $python $core @($TrustedV3CorePath,'materialize-loader','--precommit',$c.precommit_root,'--public-key',$public.Path,'--signer-identity',$TrustedSignerIdentity,'--ssh-keygen',$ssh.Path,'--output',$materializedTemp)
  $materialized=[IO.File]::ReadAllText($materializedTemp)|ConvertFrom-Json;if($materialized.schema_version-cne'finex-phase-b-materialized-loader-v3'){throw 'PHASE_D_V3_MATERIALIZED_INVALID'};$loader=$materialized.decoded_bindings;$i=$loader.runtime_invocation
  $expectedTrust=[ordered]@{consumer_host_identity_sha256=[string]$c.consumer_host_identity_sha256;expected_host_role=[string]$c.expected_host_role;host_identity_sha256=[string]$c.host_identity_sha256;joint_binding_sha256=[string]$c.joint_binding_sha256;release_identity_sha256=[string]$c.release_identity_sha256;source_host_identity_sha256=[string]$c.source_host_identity_sha256}
  if(($loader.trust_binding|ConvertTo-Json -Compress)-cne($expectedTrust|ConvertTo-Json -Compress)-or$loader.operator_role-cne$c.operator_role-or$i.task_name-cne$c.task_name-or$i.task_path-cne$c.task_path){throw 'PHASE_D_V3_STATUS_ROLE_BINDING_MISMATCH'}
  $signedPaths=@{python_path=$TrustedPythonPath;v3_core_path=$TrustedV3CorePath;ssh_keygen_path=$TrustedSshKeygenPath;public_key_path=$TrustedPublicKeyPath;observer_path=$TrustedObserverPath;firewall_path=$c.firewall_json;config_and_key_bindings_path=$c.config_and_key_bindings_json;attestation_path=$c.attestation_path;attestation_signature_path=$c.attestation_signature_path}
  $signedHashes=@{python_sha256=$TrustedPythonSha256;v3_core_sha256=$TrustedV3CoreSha256;ssh_keygen_sha256=$TrustedSshKeygenSha256;public_key_file_sha256=$TrustedPublicKeySha256;observer_sha256=$TrustedObserverSha256}
  foreach($name in $signedPaths.Keys){if([IO.Path]::GetFullPath([string]$i.$name)-cne[IO.Path]::GetFullPath([string]$signedPaths[$name])){throw 'PHASE_D_V3_STATUS_BINDING_MISMATCH'}};foreach($name in $signedHashes.Keys){if([string]$i.$name-cne[string]$signedHashes[$name]){throw 'PHASE_D_V3_STATUS_BINDING_MISMATCH'}}
  $observer=HOLD $TrustedObserverPath $TrustedObserverSha256 'PHASE_D_V3_OBSERVER_IDENTITY_MISMATCH';$holds.Add($observer);. ([ScriptBlock]::Create([Text.Encoding]::UTF8.GetString($observer.Bytes)))
  $fw=Get-Content -Raw -LiteralPath $c.firewall_json|ConvertFrom-Json;$keys=Get-Content -Raw -LiteralPath $c.config_and_key_bindings_json|ConvertFrom-Json;$live=Get-PhaseBV3WindowsTopology $c.task_name $c.task_path $fw $keys
  $encoded=[regex]::Match([string]$live.action.arguments,'-EncodedCommand ([A-Za-z0-9+/=]+)$');if(-not$encoded.Success-or$encoded.Groups[1].Value-cne$materialized.encoded_command){throw 'PHASE_D_V3_LOADER_INVALID'}
  $temp=[IO.Path]::GetTempFileName();Write-PhaseBV3CanonicalJson $live $temp;if($live.state-ceq'Disabled'){$command='verify-activation';$extra=@('--output',$temp+'.verified')}elseif($live.state-ceq'Running'){$command='verify-runtime-readiness';$extra=@('--readiness',$c.readiness_path,'--readiness-public-key',$c.readiness_public_key,'--readiness-identity',$c.readiness_identity)}else{throw 'PHASE_D_V3_LIFECYCLE_INVALID'}
  try{PY $python $core (@($TrustedV3CorePath,$command,'--precommit',$c.precommit_root,'--live-topology',$temp,'--public-key',$public.Path,'--signer-identity',$TrustedSignerIdentity,'--ssh-keygen',$ssh.Path,'--attestation',$c.attestation_path,'--attestation-signature',$c.attestation_signature_path)+$extra);$valid=$true}catch{$valid=$false}
  $results+=[ordered]@{lifecycle=[string]$live.state;role=[string]$c.operator_role;valid=$valid}
 }finally{$cleanup=@($materializedTemp);if($null-ne$temp){$cleanup+=@($temp,($temp+'.verified'))};Remove-Item $cleanup -Force -ErrorAction SilentlyContinue;foreach($held in $holds){$held.Stream.Dispose()}}
}
[ordered]@{ready_for_activation=@($results|Where-Object{$_.lifecycle-ne'Disabled'-or-not$_.valid}).Count-eq0;ready_for_runtime=@($results|Where-Object{$_.lifecycle-ne'Running'-or-not$_.valid}).Count-eq0;roles=$results;schema_version='finex-phase-d-status-v3'}|ConvertTo-Json -Compress -Depth 16
